package attackflow

import (
	"fmt"

	"github.com/google/uuid"
)

type AttackFlow struct {
	SDO       `json:",inline"`
	StartRefs []string `json:"start_refs"`
	Scope     string   `json:"scope"`
}

type AttackFlowObject interface {
	StixObject
	Append(AttackFlowObject) AttackFlowObject
}

func NewAttackFlow(name, description string) (AttackFlow, Identity) {
	// TODO: allow customization of the Creator
	creatorSDO := NewSDO("identity", "Ran", "Generated by Ran", false)
	extRef := ExternalReference{
		SourceName:  "Ran",
		Description: "Adversary Emulation Tool",
		URL:         "https://github.com/Magier/Ran",
	}
	creatorSDO.ExternalReferences = []ExternalReference{extRef}
	creator := Identity{
		SDO:                creatorSDO,
		IdentityClass:      Individual,
		ContactInformation: "xd70lz7pz@mozmail.com",
	}

	afSDO := NewSDO("attack-flow", name, description, true)
	afSDO.CreatedByRef = creator.ID
	afSDO.ExternalReferences = []ExternalReference{extRef}
	af := AttackFlow{
		StartRefs: []string{},
		SDO:       afSDO,
		Scope:     "campaign",
	}

	return af, creator
}

var _ AttackFlowObject = (*AttackFlow)(nil)

func (f AttackFlow) Append(obj AttackFlowObject) AttackFlowObject {
	f.StartRefs = append(f.StartRefs, obj.GetID())
	return f
}

// Attack Flow is an extension to STIX Objects:
// https://center-for-threat-informed-defense.github.io/attack-flow/language/#attack-flow-sdos

type AttackAction struct {
	SDO          `json:",inline"`
	TacticID     string   `json:"tactic_id"`
	TacticRef    string   `json:"tactic_ref"`
	TechniqueID  string   `json:"technique_id"`
	TechniqueRef string   `json:"technique_ref"`
	EffectRefs   []string `json:"effect_refs,omitempty"`
}

func NewAttackAction(name, description, tactic, technique string) AttackAction {
	sdo := NewSDO("attack-action", name, description, true)
	return AttackAction{
		SDO:          sdo,
		TacticID:     tactic,
		TacticRef:    fmt.Sprintf("x-mitre-tactic--%s", uuid.New()),
		TechniqueID:  technique,
		TechniqueRef: fmt.Sprintf("attack-pattern--%s", uuid.New()),
		EffectRefs:   []string{},
	}
}
func (f AttackAction) Append(obj AttackFlowObject) AttackFlowObject {
	f.EffectRefs = append(f.EffectRefs, obj.GetID())
	return f
}

var _ AttackFlowObject = (*AttackAction)(nil)

type AttackAsset struct {
	SDO       `json:",inline"`
	ObjectRef string `json:"object_ref"`
}

var _ AttackFlowObject = (*AttackAsset)(nil)

func (f AttackAsset) Append(obj AttackFlowObject) AttackFlowObject {
	f.ObjectRef = obj.GetID()
	return f
}

var _ AttackFlowObject = (*AttackAction)(nil)

type AttackCondition struct {
	SDO            `json:",inline"`
	OnTrueRefs     []string `json:"on_true_refs"`
	OnFalseRefs    []string `json:"on_false_refs"`
	Pattern        string   `json:"pattern"`
	PatternType    string   `json:"pattern_type"`
	PatternVersion string   `json:"pattern_version"`
}

var _ AttackFlowObject = (*AttackCondition)(nil)

func (op AttackCondition) Append(obj AttackFlowObject) AttackFlowObject {
	// TODO: properly introduce branching condition
	op.OnTrueRefs = append(op.OnTrueRefs, obj.GetID())
	return op
}

type AttackOperator struct {
	SDO        `json:",inline"`
	Operator   string   `json:"operator"`
	EffectRefs []string `json:"effect_refs,omitempty"`
}

var _ AttackFlowObject = (*AttackOperator)(nil)

func (op AttackOperator) Append(obj AttackFlowObject) AttackFlowObject {
	op.EffectRefs = append(op.EffectRefs, obj.GetID())
	return op
}
