package attackflow

import (
	"fmt"
	"time"

	"github.com/google/uuid"
)

type AttackFlow struct {
	SDO       `json:",inline"`
	StartRefs []string `json:"start_refs"`
	Scope     string   `json:"scope"`
}

type AttackFlowObject interface {
	StixObject
	Append(AttackFlowObject) AttackFlowObject
}

func NewAttackFlow(name, description string) (AttackFlow, Identity) {
	// TODO: allow customization of the Creator
	creatorSDO := NewSDO("identity", "Ran", "Generated by Ran", false)
	extRef := ExternalReference{
		SourceName:  "Ran",
		Description: "Adversary Emulation Tool",
		URL:         "https://github.com/Magier/Ran",
	}
	creatorSDO.ExternalReferences = []ExternalReference{extRef}
	creator := Identity{
		SDO:                creatorSDO,
		IdentityClass:      Individual,
		ContactInformation: "xd70lz7pz@mozmail.com",
	}

	afSDO := NewSDO("attack-flow", name, description, true)
	afSDO.CreatedByRef = creator.ID
	afSDO.ExternalReferences = []ExternalReference{extRef}
	af := AttackFlow{
		StartRefs: []string{},
		SDO:       afSDO,
		Scope:     "campaign",
	}

	return af, creator
}

var _ AttackFlowObject = (*AttackFlow)(nil)

func (f AttackFlow) Append(obj AttackFlowObject) AttackFlowObject {
	f.StartRefs = append(f.StartRefs, obj.GetID())
	return f
}

// Attack Flow is an extension to STIX Objects:
// https://center-for-threat-informed-defense.github.io/attack-flow/language/#attack-flow-sdos

type AttackAction struct {
	SDO            `json:",inline"`
	TacticID       string    `json:"tactic_id"`
	TacticRef      string    `json:"tactic_ref"`
	TechniqueID    string    `json:"technique_id"`
	TechniqueRef   string    `json:"technique_ref"`
	CommandRef     string    `json:"command_ref,omitempty"`
	AssetRefs      []string  `json:"asset_refs,omitempty"`
	EffectRefs     []string  `json:"effect_refs,omitempty"`
	ExecutionStart Timestamp `json:"execution_start,omitempty"`
	ExecutionEnd   Timestamp `json:"execution_end,omitempty"`
}

func NewAttackAction(name, description, tactic, technique, cmd string, execStart, execEnd time.Time) (AttackAction, []StixObject) {
	sdo := NewSDO("attack-action", name, description, true)
	observables := []StixObject{}

	var proc Process
	if cmd != "" {
		proc = Process{
			SCO:         NewSCO("process"),
			CommandLine: cmd,
			CreatedTime: Timestamp(execStart), // this is not the exact timestamp, but hopefully close enough
		}
		observables = append(observables, proc)
	}

	return AttackAction{
		SDO:            sdo,
		TacticID:       tactic,
		TacticRef:      fmt.Sprintf("x-mitre-tactic--%s", uuid.New()),
		TechniqueID:    technique,
		TechniqueRef:   fmt.Sprintf("attack-pattern--%s", uuid.New()),
		ExecutionStart: Timestamp(execStart),
		ExecutionEnd:   Timestamp(execEnd),
		EffectRefs:     []string{},
		AssetRefs:      []string{},
		CommandRef:     proc.ID,
	}, observables
}
func (f AttackAction) Append(obj AttackFlowObject) AttackFlowObject {
	f.EffectRefs = append(f.EffectRefs, obj.GetID())
	return f
}

var _ AttackFlowObject = (*AttackAction)(nil)

type AttackAsset struct {
	SDO       `json:",inline"`
	ObjectRef string `json:"object_ref,omitempty"`
}

func NewAttackAsset(name, description string) AttackAsset {
	return AttackAsset{
		SDO: NewSDO("attack-asset", name, description, true),
	}
}

var _ AttackFlowObject = (*AttackAsset)(nil)

func (f AttackAsset) Append(obj AttackFlowObject) AttackFlowObject {
	f.ObjectRef = obj.GetID()
	return f
}

var _ AttackFlowObject = (*AttackAction)(nil)

type AttackCondition struct {
	SDO            `json:",inline"`
	OnTrueRefs     []string `json:"on_true_refs"`
	OnFalseRefs    []string `json:"on_false_refs"`
	Pattern        string   `json:"pattern"`
	PatternType    string   `json:"pattern_type"`
	PatternVersion string   `json:"pattern_version"`
}

var _ AttackFlowObject = (*AttackCondition)(nil)

func (op AttackCondition) Append(obj AttackFlowObject) AttackFlowObject {
	// TODO: properly introduce branching condition
	op.OnTrueRefs = append(op.OnTrueRefs, obj.GetID())
	return op
}

type AttackOperator struct {
	SDO        `json:",inline"`
	Operator   string   `json:"operator"`
	EffectRefs []string `json:"effect_refs,omitempty"`
}

var _ AttackFlowObject = (*AttackOperator)(nil)

func (op AttackOperator) Append(obj AttackFlowObject) AttackFlowObject {
	op.EffectRefs = append(op.EffectRefs, obj.GetID())
	return op
}
