name: Delete Deployment
description: Delete a deployment
tactic: Impact
techniques:
  - Service Stop
  - T1489
parameters:
  K8S_AUTH:
    type: K8sAuth
    description: the Kubernetes identity selected by Authenticate As
  Name:
    type: string
    default: ${TARGET}
    description: the name of the deployment to delete
  Namespace:
    type: string
    default: ${NS}
    description: the name of the namespace of the deployment
procedures:
  - key: kubectl
    command: >
      kubectl delete deployment {{ Name }}  --namespace={{ Namespace }} ${K8S_AUTH}
preconditions:
  kind: Deployment
  rbac: 
    - verb: delete
      resource: deployments
effects:
  - "delete k8s.deployment"
# cmd: {}
# defend: {}
refernces:
