/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get attack graph
         * @description Returns the current attack graph with nodes and edges
         */
        get: operations["getGraph"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaign-state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get campaign state
         * @description Returns the current campaign state with entities and relations
         */
        get: operations["getCampaignState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/armory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get armory
         * @description Returns all available TTPs (Tactics, Techniques, and Procedures). Optionally filter by tactic.
         */
        get: operations["getArmory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applicable-ttps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get applicable TTPs for a target
         * @description Returns TTPs that can be applied to the specified target. If targetId is omitted or empty, returns TTPs for all targets.
         */
        get: operations["getApplicableTTPs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/flow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get attack flow
         * @description Returns the attack flow with steps and edges
         */
        get: operations["getFlow"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/flow/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export attack flow
         * @description Returns the attack flow in MITRE ATT&CK Flow format
         */
        get: operations["exportAttackFlow"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/flow/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save attack flow
         * @description Save the attack flow to a file
         */
        post: operations["saveFlow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/action/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute action
         * @description Execute a TTP action on a target. The action will be queued and executed asynchronously. The final execution status will be sent via SSE.
         */
        post: operations["executeAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaign/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset campaign
         * @description Reset the current campaign state
         */
        post: operations["resetCampaign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pods/running": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get running pods
         * @description Returns list of running pods in the specified namespace
         */
        get: operations["getRunningPods"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pods/watch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start watching pods
         * @description Starts a real-time watch on pods. Pod state changes will be pushed via SSE as 'pods-changed' events.
         */
        post: operations["startPodWatch"];
        /**
         * Stop watching pods
         * @description Stops the current pod watch. No more 'pods-changed' SSE events will be sent.
         */
        delete: operations["stopPodWatch"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/execution-records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get execution records
         * @description Returns all execution records for the current campaign session.
         *     Each record includes the full raw stdout/stderr in `results`, resolved
         *     arguments, timing, and the parse audits produced by each declared TTP
         *     effect. Intended for use by Shuhari's Gap 2 scanner,
         *     which cross-references raw stdout against declared effects to detect
         *     undeclared structured output.
         */
        get: operations["getExecutionRecords"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/execution-records/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get execution record by ID
         * @description Returns a single execution record by command ID, joined with its parse audits.
         */
        get: operations["getExecutionRecordById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get file content
         * @description Returns the content of a previously read file
         */
        get: operations["getFileContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export interface webhooks {
    "armory-loaded": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Armory loaded webhook
         * @description Triggered when the armory is successfully loaded
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: date-time */
                        timestamp?: string;
                    };
                };
            };
            responses: {
                /** @description Webhook received successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid webhook payload */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export interface components {
    schemas: {
        Graph: {
            nodes: components["schemas"]["Node"][];
            edges: components["schemas"]["Edge"][];
            rootNodeId: string;
        };
        Node: {
            id: string;
            name: string;
            kind: string;
            parent?: string;
            accessLevel?: string;
            entityId: string;
            entity?: {
                [key: string]: unknown;
            };
            compromised?: boolean;
            isRunning?: boolean;
        };
        Edge: {
            id: string;
            name: string;
            /** Format: float */
            weight?: number;
            relation?: {
                [key: string]: unknown;
            };
            sourceId: string;
            targetId: string;
        };
        CampaignState: {
            entities: {
                [key: string]: Record<string, never>;
            };
            relations: {
                [key: string]: unknown;
            }[];
        };
        AttackFlow: {
            steps: components["schemas"]["AttackStep"][];
            edges: components["schemas"]["Edge"][];
            rootNodeId: string;
        };
        AttackStep: {
            id: string;
            targetId: string;
            command: string;
            args: {
                [key: string]: string;
            };
            procedureId: string;
            TTP: components["schemas"]["TTP"];
            results: string[];
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            completedAt: string;
            executedOn: string;
            /** @enum {string} */
            status: "Unknown" | "Failed" | "Success" | "Ongoing";
            observables: string[];
            defense?: components["schemas"]["TTPDefense"];
        };
        TTP: {
            id: string;
            name: string;
            description: string;
            tactic: string;
            techniques: string[];
            status: components["schemas"]["TTPStatus"];
            params: components["schemas"]["TTPParam"][];
            requires: components["schemas"]["Requirements"];
            effects?: string[];
            procedures: components["schemas"]["Procedure"][];
        };
        Procedure: {
            id: string;
            command: string;
            tool?: string;
            isLocalCommand?: boolean;
        };
        TTPParam: {
            name: string;
            type: string;
            description: string;
            required: boolean;
            default: string;
        };
        TTPDefense: {
            id: string;
            name: string;
            url?: string;
            description?: string;
            sigma?: components["schemas"]["SigmaRule"];
            d3efend?: string;
        };
        SigmaRule: {
            title: string;
            id?: string;
            description?: string;
            status?: string;
            logsource: {
                [key: string]: unknown;
            };
            detection: {
                [key: string]: unknown;
            };
            tags: string[];
            references?: string[];
            /** Format: date-time */
            date: string;
        };
        ExecuteActionCmd: {
            actionId: string;
            execSystemId?: string;
            targetId: string;
            procedureId?: string;
            args?: {
                [key: string]: string;
            };
        };
        K8sResource: {
            id: string;
            name: string;
            namespace?: string;
            kind: string;
            /** @description Pod phase (Running, Pending, Succeeded, Failed, Unknown) */
            phase?: string;
            /** @description Whether all containers in the pod are ready */
            ready?: boolean;
            /** @description Container-level state reason (e.g. CrashLoopBackOff, ImagePullBackOff) */
            stateReason?: string;
        };
        Requirements: {
            kind?: string;
            rbacPermissions?: components["schemas"]["RBACPermission"][];
            accessLevel?: string;
            exists?: string[];
        };
        RBACPermission: {
            resource: string;
            resourceName: string;
            resourceType: string;
            apiGroup: string;
            verb: string;
            scope: string;
            sourceRole: string;
            /** @default true */
            isNamespaced: boolean;
        };
        /**
         * @description A completed TTP execution joined with the parse audits produced by its
         *     declared effects. The record fields are flattened at the top level;
         *     `parseAudits` is the list of per-effect audit entries.
         */
        ExecutionRecordEntry: {
            /** @description Unique command ID, correlates with SSE `ttp-executed` and `parse-audited` events */
            id: string;
            ttp_id: string;
            ttp_name: string;
            tactic: string;
            target_id: string;
            /** @description ID of the system that ran the command; empty for direct builtin exec */
            exec_system_id: string;
            procedure_id: string;
            /** @description Fully grounded command string sent to the C2 backend */
            command: string;
            /** @description Resolved arguments after default-filling and template substitution */
            args: {
                [key: string]: string;
            };
            success: boolean;
            exit_code: number;
            /** @description Raw output lines — first element is stdout, second (if present) is stderr */
            results: string[];
            fail_reason: string;
            /**
             * Format: int64
             * @description Unix timestamp in milliseconds when the command was dispatched
             */
            started_at_ms: number;
            /**
             * Format: int64
             * @description Unix timestamp in milliseconds when the result was received
             */
            completed_at_ms: number;
            parseAudits: components["schemas"]["ParseAudit"][];
        };
        /**
         * @description Audit record for a single effect parse attempt. `parse_result` indicates
         *     whether the effect was parsed successfully; `NoParser` and `UnknownFormat`
         *     are the two signals used by Shuhari's Gap 1 classifier.
         */
        ParseAudit: {
            /** @description Command ID of the execution that produced this audit */
            cmd_id: string;
            /** @description Effect identifier as declared in the TTP (e.g. `sys.envvar`, `k8s.podlist`) */
            effect_id: string;
            ttp_id: string;
            target_id: string;
            parser_version: string;
            /** @description SHA-256 of the raw stdout+stderr, for deduplication across episodes */
            raw_output_hash: string;
            /** @description First 1024 characters of combined stdout+stderr */
            raw_output_preview: string;
            /**
             * @description - `Parsed`: effect was handled and facts were written to the campaign
             *     - `KnownFailure`: effect ran but produced expected-empty output (e.g. command not found)
             *     - `UnknownFormat`: output was present but the parser could not interpret it
             *     - `NoParser`: no compiled or external parser is registered for this effect (Gap 1 signal)
             *     - `ParserBug`: parser crashed or panicked
             * @enum {string}
             */
            parse_result: "Parsed" | "KnownFailure" | "UnknownFormat" | "NoParser" | "ParserBug";
            /** @description Human-readable explanation of the parse outcome */
            detail: string;
            /** @description Number of new entities or field updates written to the campaign graph */
            inferred_facts_written: number;
        };
        Error: {
            error: string;
            details?: string;
        };
        /** @description Reference to the Kubernetes owner of a resource (e.g. ReplicaSet → Pod). */
        OwnerRef: {
            name: string;
            kind: string;
            uid: string;
        };
        /** @description A volume mount on a pod — either a projected volume or a host-path bind mount. */
        VolumeMount: {
            name: string;
            /** @description Path inside the container where the volume appears. */
            mount_point: string;
            /** @description Path on the host that is bound (for hostPath mounts). */
            mount_root: string;
            mount_type?: string;
            read_only: boolean;
            is_host_path: boolean;
        };
        /**
         * @description Status of a TTP - whether it is enabled or disabled
         * @enum {string}
         */
        TTPStatus: "enabled" | "disabled";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getGraph: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Graph"];
                };
            };
        };
    };
    getCampaignState: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignState"];
                };
            };
        };
    };
    getArmory: {
        parameters: {
            query?: {
                /** @description Optional tactic to filter by (e.g., "Execution", "CredentialAccess") */
                tactic?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TTP"][];
                };
            };
        };
    };
    getApplicableTTPs: {
        parameters: {
            query?: {
                /** @description ID of the target entity (optional, can be empty for all targets) */
                targetId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TTP"][];
                };
            };
            /** @description Target not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getFlow: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttackFlow"];
                };
            };
        };
    };
    exportAttackFlow: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Export failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    saveFlow: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description File path to save the flow */
                    path: string;
                };
            };
        };
        responses: {
            /** @description Successfully saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                    };
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    executeAction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExecuteActionCmd"];
            };
        };
        responses: {
            /** @description Action executed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: string;
                    };
                };
            };
            /** @description Action queued for execution, pending asynchronous processing. The final status will be sent via SSE. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: string;
                        taskId?: string;
                    };
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The specified action or target was not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The action was executed, but failed for some reason */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    resetCampaign: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Campaign reset successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: string;
                    };
                };
            };
            /** @description Reset failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getRunningPods: {
        parameters: {
            query?: {
                /** @description Kubernetes namespace (optional, defaults to all namespaces) */
                namespace?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["K8sResource"][];
                };
            };
            /** @description Failed to retrieve pods */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    startPodWatch: {
        parameters: {
            query?: {
                /** @description Kubernetes namespace to watch (optional, defaults to all namespaces) */
                namespace?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Watch started successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: string;
                    };
                };
            };
            /** @description Failed to start watch */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    stopPodWatch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Watch stopped successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: string;
                    };
                };
            };
        };
    };
    getExecutionRecords: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionRecordEntry"][];
                };
            };
        };
    };
    getExecutionRecordById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Command ID (matches the `id` field in SSE `ttp-executed` and `parse-audited` events) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionRecordEntry"];
                };
            };
            /** @description No record found for the given ID */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getFileContent: {
        parameters: {
            query: {
                /** @description The file path to retrieve content for */
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File content retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        path?: string;
                        content?: string;
                    };
                };
            };
            /** @description File content not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
