/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get attack graph
         * @description Returns the current attack graph with nodes and edges
         */
        get: operations["getGraph"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaign-state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get campaign state
         * @description Returns the current campaign state with entities and relations
         */
        get: operations["getCampaignState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/armory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get armory
         * @description Returns all available TTPs (Tactics, Techniques, and Procedures)
         */
        get: operations["getArmory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applicable-ttps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get applicable TTPs for a target
         * @description Returns TTPs that can be applied to the specified target. If targetId is omitted or empty, returns TTPs for all targets.
         */
        get: operations["getApplicableTTPs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/flow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get attack flow
         * @description Returns the attack flow with steps and edges
         */
        get: operations["getFlow"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/flow/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export attack flow
         * @description Returns the attack flow in MITRE ATT&CK Flow format
         */
        get: operations["exportAttackFlow"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/flow/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save attack flow
         * @description Save the attack flow to a file
         */
        post: operations["saveFlow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/action/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute action
         * @description Execute a TTP action on a target
         */
        post: operations["executeAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaign/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset campaign
         * @description Reset the current campaign state
         */
        post: operations["resetCampaign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pods/running": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get running pods
         * @description Returns list of running pods in the specified namespace
         */
        get: operations["getRunningPods"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export interface webhooks {
    "armory-loaded": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Armory loaded webhook
         * @description Triggered when the armory is successfully loaded
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: date-time */
                        timestamp?: string;
                    };
                };
            };
            responses: {
                /** @description Webhook received successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid webhook payload */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export interface components {
    schemas: {
        Graph: {
            nodes: components["schemas"]["Node"][];
            edges: components["schemas"]["Edge"][];
            rootNodeId: string;
        };
        Node: {
            id: string;
            name: string;
            kind: string;
            parent?: string;
            accessLevel?: string;
            entityId: string;
            entity?: {
                [key: string]: unknown;
            };
            compromised?: boolean;
        };
        Edge: {
            id: string;
            name: string;
            /** Format: float */
            weight?: number;
            relation?: {
                [key: string]: unknown;
            };
            sourceId: string;
            targetId: string;
        };
        CampaignState: {
            entities: {
                [key: string]: Record<string, never>;
            };
            relations: {
                [key: string]: unknown;
            }[];
        };
        AttackFlow: {
            steps: components["schemas"]["AttackStep"][];
            edges: components["schemas"]["Edge"][];
            rootNodeId: string;
        };
        AttackStep: {
            id: string;
            targetId: string;
            command: string;
            args: {
                [key: string]: string;
            };
            procedureId: string;
            TTP: components["schemas"]["TTP"];
            results: string[];
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            completedAt: string;
            executedOn: string;
            success: boolean;
            observables: string[];
        };
        TTP: {
            id: string;
            name: string;
            description: string;
            tactic: string;
            techniques: string[];
            status: components["schemas"]["TTPStatus"];
            params: components["schemas"]["TTPParam"][];
            requires: components["schemas"]["Requirements"];
            effects?: string[];
            procedures: components["schemas"]["Procedure"][];
            defense?: components["schemas"]["TTPDefense"];
        };
        Procedure: {
            id: string;
            command: string;
            tool?: string;
            isLocalCommand?: boolean;
        };
        TTPParam: {
            name: string;
            type: string;
            description: string;
            required: boolean;
            default: string;
        };
        TTPDefense: {
            id: string;
            name: string;
            url?: string;
            description?: string;
            sigma?: components["schemas"]["SigmaRule"];
            d3efend?: string;
        };
        SigmaRule: {
            title: string;
            id?: string;
            description?: string;
            status?: string;
            logsource: {
                [key: string]: unknown;
            };
            detection: {
                [key: string]: unknown;
            };
            tags: string[];
            references?: string[];
            /** Format: date-time */
            date: string;
        };
        ExecuteActionCmd: {
            actionId: string;
            targetId: string;
            procedureId?: string;
            args?: {
                [key: string]: string;
            };
        };
        K8sResource: {
            id: string;
            name: string;
            namespace?: string;
            kind: string;
        };
        Requirements: {
            kind?: string;
            rbacPermissions?: components["schemas"]["RBACPermission"][];
            accessLevel?: string;
            exists?: string[];
        };
        RBACPermission: {
            resource: string;
            resourceName: string;
            resourceType: string;
            apiGroup: string;
            verb: string;
            scope: string;
            sourceRole: string;
        };
        Error: {
            error: string;
            details?: string;
        };
        /**
         * @description Status of a TTP - whether it is enabled or disabled
         * @enum {string}
         */
        TTPStatus: "enabled" | "disabled";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getGraph: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Graph"];
                };
            };
        };
    };
    getCampaignState: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignState"];
                };
            };
        };
    };
    getArmory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TTP"][];
                };
            };
        };
    };
    getApplicableTTPs: {
        parameters: {
            query?: {
                /** @description ID of the target entity (optional, can be empty for all targets) */
                targetId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TTP"][];
                };
            };
            /** @description Target not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getFlow: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttackFlow"];
                };
            };
        };
    };
    exportAttackFlow: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Export failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    saveFlow: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description File path to save the flow */
                    path: string;
                };
            };
        };
        responses: {
            /** @description Successfully saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                    };
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    executeAction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExecuteActionCmd"];
            };
        };
        responses: {
            /** @description Action executed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: string;
                    };
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    resetCampaign: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Campaign reset successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: string;
                    };
                };
            };
            /** @description Reset failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getRunningPods: {
        parameters: {
            query?: {
                /** @description Kubernetes namespace (optional, defaults to all namespaces) */
                namespace?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["K8sResource"][];
                };
            };
            /** @description Failed to retrieve pods */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
