name: zrok
description: zrok is a tool for securely exposing local services to the internet using encrypted tunnels.

functions:
  share_reserve:
    description: start a backend for a reserved share
    parameters:
      shareToken:
        type: string
        required: true
        description: to token to identify the shaee
