[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ran"
path = "src/main.rs"

[dependencies]
anyhow = "1"
armory = { path = "../armory" }
async-trait = "0.1"
api = { path = "../api" }
axum = "0.7"
c2 = { path = "../c2" }
campaign = { path = "../campaign" }
clap = { version = "4", features = ["derive"] }
k8s = { path = "../k8s" }
serde_yaml = "0.9"
ran-domain = { path = "../domain" }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal", "net", "sync", "process", "io-util"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
