[package]
name = "cli"
version.workspace = true
edition = "2021"

[[bin]]
name = "ran"
path = "src/main.rs"

[features]
bundled-armory = ["app/bundled-armory"]

[dependencies]
anyhow = "1"
app = { path = "../app" }
armory = { path = "../armory" }
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
rustls = { version = "0.23", default-features = false, features = ["aws-lc-rs"] }
