name: Read Kubelet.config
description: Reads the kubelet.conf from the filesystem of a node
tactic: Credential Access
techniques: ["Steal Application Access Token", "T1528"]
parameters:
  PATH:
    type: string
    description: the path to the service account
    default: "/etc/kubernetes/kubelet.conf"
procedures:
  - key: cat
    command: cat ${PATH}
  - key: sliver
    command: get_file ${PATH}
preconditions:
  accessLevel: user-read
  kind: Node
effects:
  - file:kubelet.config

# dependencies:
#   - type: Kubernetes Pod
#     description: A running Kubernetes pod with a mounted service account token.
indicators:
  - type: File
    description: The service account token file
    location: /var/run/secrets/kubernetes.io/serviceaccount/token
references:
  - https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/#accessing-the-api-from-a-pod
