// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetID():Promise<string>;

export function IsEvent():Promise<void>;

export function String():Promise<string>;

export function UiMessage():Promise<string>;
