// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetID() {
  return window['go']['domain']['ErrorMsg']['GetID']();
}

export function IsEvent() {
  return window['go']['domain']['ErrorMsg']['IsEvent']();
}

export function String() {
  return window['go']['domain']['ErrorMsg']['String']();
}

export function UiMessage() {
  return window['go']['domain']['ErrorMsg']['UiMessage']();
}
