package planner

import (
	"context"
	"fmt"
	"log/slog"
	"os"
	"time"

	"github.com/Magier/Ran/armory"
	"github.com/Magier/Ran/domain"
	bus "github.com/Magier/Ran/internal/bus"
	attackflow "github.com/Magier/Ran/mitre/attack_flow"
)

type Planner interface {
	Execute(context.Context)
}

func CreatePlanner(path string, armory armory.Armory, mb bus.MessageBus) Planner {
	p := LoadPlan(path, armory)
	p.bus = mb
	return p
}

type PlayBookPlanner struct {
	Steps []domain.ActionSelected
	bus   bus.MessageBus
}

var _ Planner = (*PlayBookPlanner)(nil)

func LoadPlan(path string, armory armory.Armory) PlayBookPlanner {
	data, err := os.ReadFile(path)
	if err != nil {
		slog.Error(err.Error())
		return PlayBookPlanner{}
	}

	af, err := attackflow.UnmarshalStixBundle(data)
	if err != nil {
		slog.Error(err.Error())
	}

	steps := []domain.ActionSelected{}

	attackflow.TraverseAttackFlow(af, func(action attackflow.StixObject) {
		switch o := action.(type) {
		case attackflow.AttackAction:
			ttp, ok := lookupTTPInArmory(o, armory)
			if !ok {
				return
			}
			step := domain.ActionSelected{
				ActionID: ttp.GetID(),
			}

			if len(o.AssetRefs) > 1 {
				slog.Warn(fmt.Sprintf("AttackAction %s has %d asset refs", o.Name, len(o.AssetRefs)))
			}
			for _, id := range o.AssetRefs {
				if a, ok := af.Objects[id].(attackflow.AttackAsset); ok {
					step.TargetID = a.Name
				} else {
					slog.Error(fmt.Sprintf("Could not convert %s to AttackAsset", id))
				}
			}

			if cmd, ok := af.Objects[o.CommandRef].(attackflow.Process); ok {
				step.Variant = cmd.CommandLine
			} else {
				slog.Error(fmt.Sprintf("Could not convert %s to Process", o.CommandRef))
			}

			steps = append(steps, step)
		}
	})

	return PlayBookPlanner{Steps: steps}
}

func (p PlayBookPlanner) Execute(ctx context.Context) {
	// the channel signals when a new TTP is executed
	flowControl := make(chan bool, 1)
	subscribe := func(msgType domain.Message, flag bool) func() {
		return p.bus.Subscribe(msgType, func(ctx context.Context, msg domain.Message) (domain.Message, error) {
			flowControl <- flag
			return nil, nil
		})
	}
	unsubs := []func(){
		subscribe(domain.RanReady{}, true), // simplified starting point of the Planner
		subscribe(domain.TTPExecuted{}, true),
		subscribe(domain.TTPFailed{}, false),
	}
	stopPlanner := func() {
		for _, unsub := range unsubs {
			unsub()
		}
	}
	defer stopPlanner()

	for i := range p.Steps {
		select {
		case <-ctx.Done():
			break
		case wasSuccess, ok := <-flowControl:
			if !ok || !wasSuccess {
				break
			}
			time.Sleep(100 * time.Millisecond)
			err := p.bus.Publish(p.Steps[i])
			if err != nil {
				slog.Error(fmt.Sprintf("Failed to publish next step in plan: %v", err))
			}
		}
	}
}

func lookupTTPInArmory(action attackflow.AttackAction, armory armory.Armory) (domain.TTP, bool) {
	for _, ttp := range armory.GetTTPs() {
		// very naive assumption, that the name is a direct match (only if flows were generated by Ran)
		if ttp.Name == action.Name {
			return ttp, true
		}

		for _, tech := range ttp.Techniques {
			if tech == action.TechniqueID {
				return ttp, true
			}
		}
	}

	return domain.TTP{}, false
}
