//go:build ignore

package main

import (
	"fmt"
	"io"
	"net/http"
	"os"

	attackflow "github.com/Magier/Ran/mitre/attack_flow"
)

func downloadFile(url string) ([]byte, error) {
	data := []byte{}

	localPath := "enterprise-attack.json"
	if _, err := os.Stat(localPath); err == nil {
		data, err = os.ReadFile(localPath)
		if err != nil {
			return data, fmt.Errorf("Error reading local file: %v", err)
		}
		return data, nil
	}

	resp, err := http.Get(url)
	if err != nil {
		return data, fmt.Errorf("Error downloading file: %v", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return data, fmt.Errorf("Error: received status: %v", resp.Status)
	}

	data, err = io.ReadAll(resp.Body)
	if err != nil {
		return data, fmt.Errorf("Error reading response body: %v", err)
	}
	return data, nil
}

func GetExternalID(ap attackflow.SDO) (string, bool) {
	for _, e := range ap.ExternalReferences {
		if e.SourceName == "mitre-attack" {
			return e.ExternalID, true
		}
	}
	return "", false
}

func main() {
	// load the official mapping between Mitre ATT&CK and STIX
	attackStixUrl := os.Args[1]

	data, err := downloadFile(attackStixUrl)
	if err != nil {
		fmt.Println("Error downloading file: ", err.Error())
		os.Exit(1)
	}

	// parse the STIX bundle
	bundle, err := attackflow.UnmarshalStixBundle(data)
	var _ = bundle
	if err != nil {
		fmt.Println("Error: ", err.Error())
	}

	tacticsStix := map[string]string{}
	techniquesStix := map[string]string{}
	techniqueIDtoName := map[string]string{}

	for _, obj := range bundle.Objects {
		switch sdo := obj.(type) {
		case attackflow.AttackPattern:
			if !sdo.Deprecated {
				techniqueID, ok := GetExternalID(sdo.SDO)
				if ok {
					techniquesStix[sdo.ID] = techniqueID
					techniqueIDtoName[techniqueID] = sdo.Name
				} else {
					fmt.Println("Error: no technique id found for attack pattern: ", sdo.Name)
				}
			}
		case attackflow.MitreTactic:
			tacticID, ok := GetExternalID(sdo.SDO)
			if ok {
				tacticsStix[sdo.ID] = tacticID
			}
		}
	}

	generateMappingFile("mitre_mappings.go", tacticsStix, techniquesStix, techniqueIDtoName)
}

func generateMappingFile(destPath string, tactics, techniques, techniqueNames map[string]string) {
	file, err := os.Create(destPath)
	if err != nil {
		fmt.Println("Error creating file:", err)
		os.Exit(1)
	}
	defer file.Close()

	// Write the generated Go code
	file.WriteString("// Code generated by go generate; DO NOT EDIT.\n")
	file.WriteString(fmt.Sprintf("package %s\n\n", "mitre"))

	// Write tactics mapping
	file.WriteString("var TacticMapping = map[string]string{\n")
	// file.WriteString("var MitreTacticMapping = map[string]mitre.Tactic{\n")
	for key, value := range tactics {
		file.WriteString(fmt.Sprintf("\t%q: %q,\n", key, value))
	}
	file.WriteString("}\n")

	// Write technique mapping
	file.WriteString("var TechniqueMapping = map[string]string{\n")
	for key, value := range techniques {
		file.WriteString(fmt.Sprintf("\t%q: %q,\n", key, value))
	}
	file.WriteString("}\n")

	// Write technique name mapping
	// file.WriteString("type Technique string\n\n")

	// file.WriteString("const (\n")
	file.WriteString("var TechniqueNameMapping = map[string]string{\n")
	for key, value := range techniqueNames {
		file.WriteString(fmt.Sprintf("\t%q: %q,\n", key, value))
	}
	file.WriteString("}\n")
}
