// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {domain} from '../models';

export function ExecuteAction(arg1:string,arg2:string,arg3:main.ActionArgs):Promise<void>;

export function GetApplicableTTPs(arg1:string):Promise<Array<domain.TTP>>;

export function GetFlow():Promise<main.AttackFlow>;

export function GetGraph():Promise<main.Graph>;

export function GetRunningPods():Promise<Array<string>>;

export function SaveFlow():Promise<boolean>;

export function StartEmulation(arg1:string):Promise<void>;
