// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {api} from '../models';
import {domain} from '../models';

export function ClientReady(arg1:context.Context):Promise<void>;

export function ExecuteAction(arg1:string,arg2:string,arg3:string,arg4:api.ActionArgs):Promise<void>;

export function GetApplicableTTPs(arg1:string):Promise<Array<domain.TTP>>;

export function GetArmory():Promise<Array<domain.TTP>>;

export function GetCampaignState():Promise<api.CampaignState>;

export function GetFacts():Promise<domain.FactsChanged>;

export function GetFlow():Promise<api.AttackFlow>;

export function GetGraph():Promise<api.Graph>;

export function GetRunningPods(arg1:string):Promise<Array<api.K8sResource>>;

export function ResetCampaign():Promise<void>;

export function SaveFlow():Promise<boolean>;

export function SetContext(arg1:context.Context):Promise<void>;
