// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetGraph():Promise<main.Graph>;

export function StartEmulation(arg1:string):Promise<boolean>;
