// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActionSelected(arg1, arg2, arg3) {
  return window['go']['main']['App']['ActionSelected'](arg1, arg2, arg3);
}

export function GetGraph() {
  return window['go']['main']['App']['GetGraph']();
}

export function GetRunningPods() {
  return window['go']['main']['App']['GetRunningPods']();
}

export function GetTrace() {
  return window['go']['main']['App']['GetTrace']();
}

export function IsActionSatisfied(arg1, arg2) {
  return window['go']['main']['App']['IsActionSatisfied'](arg1, arg2);
}

export function StartEmulation(arg1) {
  return window['go']['main']['App']['StartEmulation'](arg1);
}
