// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGraph() {
  return window['go']['main']['App']['GetGraph']();
}

export function StartEmulation(arg1) {
  return window['go']['main']['App']['StartEmulation'](arg1);
}
