// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for TTPStatus.
const (
	Disabled TTPStatus = "disabled"
	Enabled  TTPStatus = "enabled"
)

// AttackFlow defines model for AttackFlow.
type AttackFlow struct {
	Edges      []Edge       `json:"edges"`
	RootNodeId string       `json:"rootNodeId"`
	Steps      []AttackStep `json:"steps"`
}

// AttackStep defines model for AttackStep.
type AttackStep struct {
	TTP         TTP               `json:"TTP"`
	Args        map[string]string `json:"args"`
	Command     string            `json:"command"`
	CompletedAt time.Time         `json:"completedAt"`
	ExecutedOn  string            `json:"executedOn"`
	Id          string            `json:"id"`
	Observables []string          `json:"observables"`
	ProcedureId string            `json:"procedureId"`
	Results     []string          `json:"results"`
	StartedAt   time.Time         `json:"startedAt"`
	Success     bool              `json:"success"`
	TargetId    string            `json:"targetId"`
}

// CampaignState defines model for CampaignState.
type CampaignState struct {
	Entities  map[string]map[string]interface{} `json:"entities"`
	Relations []map[string]interface{}          `json:"relations"`
}

// Edge defines model for Edge.
type Edge struct {
	Id       string                  `json:"id"`
	Name     string                  `json:"name"`
	Relation *map[string]interface{} `json:"relation,omitempty"`
	SourceId string                  `json:"sourceId"`
	TargetId string                  `json:"targetId"`
	Weight   *float32                `json:"weight,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Details *string `json:"details,omitempty"`
	Error   string  `json:"error"`
}

// ExecuteActionCmd defines model for ExecuteActionCmd.
type ExecuteActionCmd struct {
	ActionId    string             `json:"actionId"`
	Args        *map[string]string `json:"args,omitempty"`
	ProcedureId *string            `json:"procedureId,omitempty"`
	TargetId    string             `json:"targetId"`
}

// Graph defines model for Graph.
type Graph struct {
	Edges      []Edge `json:"edges"`
	Nodes      []Node `json:"nodes"`
	RootNodeId string `json:"rootNodeId"`
}

// K8sResource defines model for K8sResource.
type K8sResource struct {
	Id        string  `json:"id"`
	Kind      string  `json:"kind"`
	Name      string  `json:"name"`
	Namespace *string `json:"namespace,omitempty"`
}

// Node defines model for Node.
type Node struct {
	AccessLevel *string                 `json:"accessLevel,omitempty"`
	Compromised *bool                   `json:"compromised,omitempty"`
	Entity      *map[string]interface{} `json:"entity,omitempty"`
	Id          string                  `json:"id"`
	Kind        string                  `json:"kind"`
	Name        string                  `json:"name"`
	Parent      *string                 `json:"parent,omitempty"`
}

// Procedure defines model for Procedure.
type Procedure struct {
	Command        string  `json:"command"`
	Id             string  `json:"id"`
	IsLocalCommand *bool   `json:"isLocalCommand,omitempty"`
	Tool           *string `json:"tool,omitempty"`
}

// RBACPermission defines model for RBACPermission.
type RBACPermission struct {
	ApiGroup     string `json:"apiGroup"`
	Resource     string `json:"resource"`
	ResourceName string `json:"resourceName"`
	ResourceType string `json:"resourceType"`
	Scope        string `json:"scope"`
	SourceRole   string `json:"sourceRole"`
	Verb         string `json:"verb"`
}

// Requirements defines model for Requirements.
type Requirements struct {
	AccessLevel     *string           `json:"accessLevel,omitempty"`
	Exists          *[]string         `json:"exists,omitempty"`
	Kind            *string           `json:"kind,omitempty"`
	RbacPermissions *[]RBACPermission `json:"rbacPermissions,omitempty"`
}

// SigmaRule defines model for SigmaRule.
type SigmaRule struct {
	Date        time.Time              `json:"date"`
	Description *string                `json:"description,omitempty"`
	Detection   map[string]interface{} `json:"detection"`
	Id          *string                `json:"id,omitempty"`
	Logsource   map[string]interface{} `json:"logsource"`
	References  *[]string              `json:"references,omitempty"`
	Status      *string                `json:"status,omitempty"`
	Tags        []string               `json:"tags"`
	Title       string                 `json:"title"`
}

// TTP defines model for TTP.
type TTP struct {
	Defense     *TTPDefense  `json:"defense,omitempty"`
	Description string       `json:"description"`
	Effects     []string     `json:"effects"`
	Id          string       `json:"id"`
	Name        string       `json:"name"`
	Params      []TTPParam   `json:"params"`
	Procedures  []Procedure  `json:"procedures"`
	Requires    Requirements `json:"requires"`
	Status      TTPStatus    `json:"status"`
	Tactic      string       `json:"tactic"`
	Techniques  []string     `json:"techniques"`
}

// TTPStatus defines model for TTP.Status.
type TTPStatus string

// TTPDefense defines model for TTPDefense.
type TTPDefense struct {
	D3efend     *string    `json:"d3efend,omitempty"`
	Description *string    `json:"description,omitempty"`
	Id          string     `json:"id"`
	Name        string     `json:"name"`
	Sigma       *SigmaRule `json:"sigma,omitempty"`
	Url         *string    `json:"url,omitempty"`
}

// TTPParam defines model for TTPParam.
type TTPParam struct {
	Default     string `json:"default"`
	Description string `json:"description"`
	Name        string `json:"name"`
	Required    bool   `json:"required"`
	Type        string `json:"type"`
}

// GetApplicableTTPsParams defines parameters for GetApplicableTTPs.
type GetApplicableTTPsParams struct {
	// TargetId ID of the target entity (optional, can be empty for all targets)
	TargetId *string `form:"targetId,omitempty" json:"targetId,omitempty"`
}

// SaveFlowJSONBody defines parameters for SaveFlow.
type SaveFlowJSONBody struct {
	// Path File path to save the flow
	Path string `json:"path"`
}

// GetRunningPodsParams defines parameters for GetRunningPods.
type GetRunningPodsParams struct {
	// Namespace Kubernetes namespace (optional, defaults to all namespaces)
	Namespace *string `form:"namespace,omitempty" json:"namespace,omitempty"`
}

// ExecuteActionJSONRequestBody defines body for ExecuteAction for application/json ContentType.
type ExecuteActionJSONRequestBody = ExecuteActionCmd

// SaveFlowJSONRequestBody defines body for SaveFlow for application/json ContentType.
type SaveFlowJSONRequestBody SaveFlowJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Execute action
	// (POST /api/action/execute)
	ExecuteAction(w http.ResponseWriter, r *http.Request)
	// Get applicable TTPs for a target
	// (GET /api/applicable-ttps)
	GetApplicableTTPs(w http.ResponseWriter, r *http.Request, params GetApplicableTTPsParams)
	// Get armory
	// (GET /api/armory)
	GetArmory(w http.ResponseWriter, r *http.Request)
	// Get campaign state
	// (GET /api/campaign-state)
	GetCampaignState(w http.ResponseWriter, r *http.Request)
	// Reset campaign
	// (POST /api/campaign/reset)
	ResetCampaign(w http.ResponseWriter, r *http.Request)
	// Get attack flow
	// (GET /api/flow)
	GetFlow(w http.ResponseWriter, r *http.Request)
	// Export attack flow
	// (GET /api/flow/export)
	ExportAttackFlow(w http.ResponseWriter, r *http.Request)
	// Save attack flow
	// (POST /api/flow/save)
	SaveFlow(w http.ResponseWriter, r *http.Request)
	// Get attack graph
	// (GET /api/graph)
	GetGraph(w http.ResponseWriter, r *http.Request)
	// Get running pods
	// (GET /api/pods/running)
	GetRunningPods(w http.ResponseWriter, r *http.Request, params GetRunningPodsParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Execute action
// (POST /api/action/execute)
func (_ Unimplemented) ExecuteAction(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get applicable TTPs for a target
// (GET /api/applicable-ttps)
func (_ Unimplemented) GetApplicableTTPs(w http.ResponseWriter, r *http.Request, params GetApplicableTTPsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get armory
// (GET /api/armory)
func (_ Unimplemented) GetArmory(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get campaign state
// (GET /api/campaign-state)
func (_ Unimplemented) GetCampaignState(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Reset campaign
// (POST /api/campaign/reset)
func (_ Unimplemented) ResetCampaign(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get attack flow
// (GET /api/flow)
func (_ Unimplemented) GetFlow(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Export attack flow
// (GET /api/flow/export)
func (_ Unimplemented) ExportAttackFlow(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Save attack flow
// (POST /api/flow/save)
func (_ Unimplemented) SaveFlow(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get attack graph
// (GET /api/graph)
func (_ Unimplemented) GetGraph(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get running pods
// (GET /api/pods/running)
func (_ Unimplemented) GetRunningPods(w http.ResponseWriter, r *http.Request, params GetRunningPodsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ExecuteAction operation middleware
func (siw *ServerInterfaceWrapper) ExecuteAction(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExecuteAction(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApplicableTTPs operation middleware
func (siw *ServerInterfaceWrapper) GetApplicableTTPs(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApplicableTTPsParams

	// ------------- Optional query parameter "targetId" -------------

	err = runtime.BindQueryParameter("form", true, false, "targetId", r.URL.Query(), &params.TargetId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "targetId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApplicableTTPs(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetArmory operation middleware
func (siw *ServerInterfaceWrapper) GetArmory(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetArmory(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCampaignState operation middleware
func (siw *ServerInterfaceWrapper) GetCampaignState(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCampaignState(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResetCampaign operation middleware
func (siw *ServerInterfaceWrapper) ResetCampaign(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResetCampaign(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetFlow operation middleware
func (siw *ServerInterfaceWrapper) GetFlow(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFlow(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ExportAttackFlow operation middleware
func (siw *ServerInterfaceWrapper) ExportAttackFlow(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExportAttackFlow(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SaveFlow operation middleware
func (siw *ServerInterfaceWrapper) SaveFlow(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SaveFlow(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGraph operation middleware
func (siw *ServerInterfaceWrapper) GetGraph(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGraph(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRunningPods operation middleware
func (siw *ServerInterfaceWrapper) GetRunningPods(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetRunningPodsParams

	// ------------- Optional query parameter "namespace" -------------

	err = runtime.BindQueryParameter("form", true, false, "namespace", r.URL.Query(), &params.Namespace)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRunningPods(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/action/execute", wrapper.ExecuteAction)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/applicable-ttps", wrapper.GetApplicableTTPs)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/armory", wrapper.GetArmory)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/campaign-state", wrapper.GetCampaignState)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/campaign/reset", wrapper.ResetCampaign)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/flow", wrapper.GetFlow)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/flow/export", wrapper.ExportAttackFlow)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/flow/save", wrapper.SaveFlow)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/graph", wrapper.GetGraph)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/pods/running", wrapper.GetRunningPods)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xaS2/buBb+KwTvXfQCSuzbdgaFd2nSBkE7HcMxMItOF7R0ZLOlSJWknBpF/vuAD70p",
	"W0qaTnduKJ7Hdz6eB9nvOBZZLjhwrfDiO1bxDjJif15oTeIvb5m4M//KpchBagp2DZKt+0E1ZPbHfyWk",
	"eIH/M6vlzbyw2ZtkC/g+wvqQA15gIiU5mH9LIfQHkcBNYiT4VaUl5VuzrDTk45U4c2815H1VRhd8LaiE",
	"BC8+esGR96Jlx6dqq9h8hlgbWQ3JPSDW6+Upw8wn9xEmcmt3kCShmgpO2LIlqed+z45YZBnhYayMXgYa",
	"kgtt1lMhM6LxAidEw5mmGeCovwm+QVxoSP7kQZk0rEpsFMg92bAOA4YcqMKdSxFDUsiheEtQBdMThSpN",
	"5ES3VRHHoJriN0IwINzKJ3ILOmhhh0U0wREmsYnljflZ7awjFVl+tD1vwe5pEWFjq9Iky3FtXxvqGp+m",
	"0+3Ih9h7SbKc0C2/1URD4CRzTcvfJ6hZy+z9QQIjZmc7eGF5WhYQDcoMn9jKyqaqkLc21fScHGAyJxkM",
	"MNHpmOyEEoWMh/h9hFoRvgO63bVJnDJBdE1gXmQbkGEaWk8a6hvKgihJKWQfpgQ0oSx87qDccvxQuM+C",
	"Oh3rL+yBucySvvrqLIX0Pz59nko/409+6NCHXL6WJN89VfHkIpkgxZS3ySW447bTOLpsvnulVuAYOfpE",
	"fqF84lE1CyonMYxM2P6kWEUhqy1QAWqajPwe9sAGy68UGVWQhMuKTWCHyfnkh8GUEwlc/yCMluVJ6gN1",
	"rEcZcIaq9yIm7LK3s1mVhWAjjS8tCBm+en1xuQSZUaV8du+EOafXUhT5UHtSkXlw8cNwSXEfrO1CqNuN",
	"xdCK3bgSLLy8B7kZkbNK1/yGhj8d6zu2lpa17AiC67Rl5Sgx7QTBN6qm9n6Dx0BuSFzHeXyW7PAj1JX0",
	"3L6l24ysChY4DInvuMa1pQmoWNK87DsC6xriB3UlAwePiW3N6EkCJaQggccwvVnXxcCnZDtRmKaajcj6",
	"7jOvoOl0E9HIxSpEaz/hdTulFLiCEaPflf9yRIAhTSGeegbo9EJAsvEnYr1eLs2Oo/PceHF15Qj1Ii5q",
	"p09pM9G0WAW8yNy4YGYmUw0SqtzPT1GIc7GmcRhmiHecfi2mMfxIMW0Gv9Lc0tMAoOZCC+UqepXPA4S9",
	"qunZ4e0Ls5IM5Jfj9JzKNGUS46lY1tnzPsKFZFM6lAHnHV9DR5YUTD/I9SODYmlYsGsJ1/puW03qetBY",
	"6VKmtL/vtRFIeSqclw1P8AoSpIFkiBRaZHakRYQniNgbLRT7qwGUEU629kChi+UNrnIrXhHu/7IH6Xom",
	"/P/z+fncXgTlwElO8QK/OJ+fv7D01DsL9ozkdObGpJm/7rAREUr3rfSTISJovV4itwsZS5GbrrBVJUk5",
	"HbZHSY8ZKP1aJAfXg3Ltm12S54zGdufss3LRddQ7OXZ1x9X7dtxMZXRtXS64chR7Pp9P0t8m6GBxvA9G",
	"vI2hsxOVV0vI3yGlBWM2t76caNpRaOyMHzDihu8Jowny8bCWqyLLiDw0w+zCZhYdTZwhGwZnWrsLXxP0",
	"AJl1IbkyJFFI74hGMeFoA8gKMEwXSO8AqRximto/WPqco5sUlXM6ogqJjGqDkZAIslwfIiSbolMhEWHM",
	"b1HnPfpdg76obDZbysQMGqTCi49dy2+ukEitbU4mctMgeiZy13JFpSvWnq4F/8PmfOMF/lqAPJTZb9G8",
	"cKwD1+XOp0dydGyXECiGPX7cVqREpU2Omy+fnptrhzwXGqWi4EmHnNegUU3EBhHKHFTTVWZCHk6y1MSP",
	"7Alltbxna1v1VYTWVdWPbD6u2iIb6z7bnMpfPZJ9QJ3dFXRlvTlT5V30UQjNgYkLKU1ZqkqV3YruqN6h",
	"8lLYQlhfCwcAbN+BPxLHY/C1FT0YuLa3fQBnEpRDLlxRV2b5CH49jOyG0nj865S10iRkHe5Vtd9+RlVz",
	"YKaEmjGiHSu3VGJbxyn1j6Yn6e0bMfO947R9mrSELm9Ze2S2L7JPyOHGu+/DT37tVxuVGXzLhdSTwaEc",
	"/XGzXr1BF+v138V8/vz3y3fI2Ij85Uq/RzR6Gr48ErGTVB0obj+Fos7ZMEf92nBEFNkfac5vyR560dAC",
	"EZRS1k8k5vMK7od15e30YUaKvlVvKQNklowpqjQxdYqPj1tWYHiIetLufvjReUwivG1kPutw8ot09ZYf",
	"QXJty9ev0UXei7EbXTq0T07H06F7ZHvCfOgUPDYVbr0UD04uEjWTBeeGoqcwYlRpM0H475HZbDJie9qp",
	"X8ICKK3c1qVITk4r74oNSA4aVC2yOar4iwhlswBj9UeDg0rTsn95Umk+Sj58YvkpSf2tzeYGZQlaUtiD",
	"DXyAYk1eOEkK5D4c3SvYAxO5vetxX2F/8YZ3WueL2YyJmLCdUHrxav5qjk1c7mCzE+KLe8ixTf0ZEyRx",
	"917hurGWdLsFCQm624GjqttpJvBmH4e8pB9VMOr/STPy5eX+4bWg7fJfDiUkIQa6H76ECadXjzHKycEg",
	"0gmzGwE9VuW3xtL7fwIAAP//NosWC8InAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
