// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for TTPStatus.
const (
	Disabled TTPStatus = "disabled"
	Enabled  TTPStatus = "enabled"
)

// AttackFlow defines model for AttackFlow.
type AttackFlow struct {
	Edges      []Edge       `json:"edges"`
	RootNodeId string       `json:"rootNodeId"`
	Steps      []AttackStep `json:"steps"`
}

// AttackStep defines model for AttackStep.
type AttackStep struct {
	TTP         TTP               `json:"TTP"`
	Args        map[string]string `json:"args"`
	Command     string            `json:"command"`
	CompletedAt time.Time         `json:"completedAt"`
	ExecutedOn  string            `json:"executedOn"`
	Id          string            `json:"id"`
	Observables []string          `json:"observables"`
	ProcedureId string            `json:"procedureId"`
	Results     []string          `json:"results"`
	StartedAt   time.Time         `json:"startedAt"`
	Success     bool              `json:"success"`
	TargetId    string            `json:"targetId"`
}

// CampaignState defines model for CampaignState.
type CampaignState struct {
	Entities  map[string]map[string]interface{} `json:"entities"`
	Relations []map[string]interface{}          `json:"relations"`
}

// Edge defines model for Edge.
type Edge struct {
	Id       string                  `json:"id"`
	Name     string                  `json:"name"`
	Relation *map[string]interface{} `json:"relation,omitempty"`
	SourceId string                  `json:"sourceId"`
	TargetId string                  `json:"targetId"`
	Weight   *float32                `json:"weight,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Details *string `json:"details,omitempty"`
	Error   string  `json:"error"`
}

// ExecuteActionCmd defines model for ExecuteActionCmd.
type ExecuteActionCmd struct {
	ActionId    string             `json:"actionId"`
	Args        *map[string]string `json:"args,omitempty"`
	ProcedureId *string            `json:"procedureId,omitempty"`
	TargetId    string             `json:"targetId"`
}

// Graph defines model for Graph.
type Graph struct {
	Edges      []Edge `json:"edges"`
	Nodes      []Node `json:"nodes"`
	RootNodeId string `json:"rootNodeId"`
}

// K8sResource defines model for K8sResource.
type K8sResource struct {
	Id        string  `json:"id"`
	Kind      string  `json:"kind"`
	Name      string  `json:"name"`
	Namespace *string `json:"namespace,omitempty"`
}

// Node defines model for Node.
type Node struct {
	AccessLevel *string                 `json:"accessLevel,omitempty"`
	Compromised *bool                   `json:"compromised,omitempty"`
	Entity      *map[string]interface{} `json:"entity,omitempty"`
	EntityId    string                  `json:"entityId"`
	Id          string                  `json:"id"`
	Kind        string                  `json:"kind"`
	Name        string                  `json:"name"`
	Parent      *string                 `json:"parent,omitempty"`
}

// Procedure defines model for Procedure.
type Procedure struct {
	Command        string  `json:"command"`
	Id             string  `json:"id"`
	IsLocalCommand *bool   `json:"isLocalCommand,omitempty"`
	Tool           *string `json:"tool,omitempty"`
}

// RBACPermission defines model for RBACPermission.
type RBACPermission struct {
	ApiGroup     string `json:"apiGroup"`
	Resource     string `json:"resource"`
	ResourceName string `json:"resourceName"`
	ResourceType string `json:"resourceType"`
	Scope        string `json:"scope"`
	SourceRole   string `json:"sourceRole"`
	Verb         string `json:"verb"`
}

// Requirements defines model for Requirements.
type Requirements struct {
	AccessLevel     *string           `json:"accessLevel,omitempty"`
	Exists          *[]string         `json:"exists,omitempty"`
	Kind            *string           `json:"kind,omitempty"`
	RbacPermissions *[]RBACPermission `json:"rbacPermissions,omitempty"`
}

// SigmaRule defines model for SigmaRule.
type SigmaRule struct {
	Date        time.Time              `json:"date"`
	Description *string                `json:"description,omitempty"`
	Detection   map[string]interface{} `json:"detection"`
	Id          *string                `json:"id,omitempty"`
	Logsource   map[string]interface{} `json:"logsource"`
	References  *[]string              `json:"references,omitempty"`
	Status      *string                `json:"status,omitempty"`
	Tags        []string               `json:"tags"`
	Title       string                 `json:"title"`
}

// TTP defines model for TTP.
type TTP struct {
	Defense     *TTPDefense  `json:"defense,omitempty"`
	Description string       `json:"description"`
	Effects     *[]string    `json:"effects,omitempty"`
	Id          string       `json:"id"`
	Name        string       `json:"name"`
	Params      []TTPParam   `json:"params"`
	Procedures  []Procedure  `json:"procedures"`
	Requires    Requirements `json:"requires"`

	// Status Status of a TTP - whether it is enabled or disabled
	Status     TTPStatus `json:"status"`
	Tactic     string    `json:"tactic"`
	Techniques []string  `json:"techniques"`
}

// TTPDefense defines model for TTPDefense.
type TTPDefense struct {
	D3efend     *string    `json:"d3efend,omitempty"`
	Description *string    `json:"description,omitempty"`
	Id          string     `json:"id"`
	Name        string     `json:"name"`
	Sigma       *SigmaRule `json:"sigma,omitempty"`
	Url         *string    `json:"url,omitempty"`
}

// TTPParam defines model for TTPParam.
type TTPParam struct {
	Default     string `json:"default"`
	Description string `json:"description"`
	Name        string `json:"name"`
	Required    bool   `json:"required"`
	Type        string `json:"type"`
}

// TTPStatus Status of a TTP - whether it is enabled or disabled
type TTPStatus string

// GetApplicableTTPsParams defines parameters for GetApplicableTTPs.
type GetApplicableTTPsParams struct {
	// TargetId ID of the target entity (optional, can be empty for all targets)
	TargetId *string `form:"targetId,omitempty" json:"targetId,omitempty"`
}

// SaveFlowJSONBody defines parameters for SaveFlow.
type SaveFlowJSONBody struct {
	// Path File path to save the flow
	Path string `json:"path"`
}

// GetRunningPodsParams defines parameters for GetRunningPods.
type GetRunningPodsParams struct {
	// Namespace Kubernetes namespace (optional, defaults to all namespaces)
	Namespace *string `form:"namespace,omitempty" json:"namespace,omitempty"`
}

// ExecuteActionJSONRequestBody defines body for ExecuteAction for application/json ContentType.
type ExecuteActionJSONRequestBody = ExecuteActionCmd

// SaveFlowJSONRequestBody defines body for SaveFlow for application/json ContentType.
type SaveFlowJSONRequestBody SaveFlowJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Execute action
	// (POST /api/action/execute)
	ExecuteAction(w http.ResponseWriter, r *http.Request)
	// Get applicable TTPs for a target
	// (GET /api/applicable-ttps)
	GetApplicableTTPs(w http.ResponseWriter, r *http.Request, params GetApplicableTTPsParams)
	// Get armory
	// (GET /api/armory)
	GetArmory(w http.ResponseWriter, r *http.Request)
	// Get campaign state
	// (GET /api/campaign-state)
	GetCampaignState(w http.ResponseWriter, r *http.Request)
	// Reset campaign
	// (POST /api/campaign/reset)
	ResetCampaign(w http.ResponseWriter, r *http.Request)
	// Get attack flow
	// (GET /api/flow)
	GetFlow(w http.ResponseWriter, r *http.Request)
	// Export attack flow
	// (GET /api/flow/export)
	ExportAttackFlow(w http.ResponseWriter, r *http.Request)
	// Save attack flow
	// (POST /api/flow/save)
	SaveFlow(w http.ResponseWriter, r *http.Request)
	// Get attack graph
	// (GET /api/graph)
	GetGraph(w http.ResponseWriter, r *http.Request)
	// Get running pods
	// (GET /api/pods/running)
	GetRunningPods(w http.ResponseWriter, r *http.Request, params GetRunningPodsParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Execute action
// (POST /api/action/execute)
func (_ Unimplemented) ExecuteAction(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get applicable TTPs for a target
// (GET /api/applicable-ttps)
func (_ Unimplemented) GetApplicableTTPs(w http.ResponseWriter, r *http.Request, params GetApplicableTTPsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get armory
// (GET /api/armory)
func (_ Unimplemented) GetArmory(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get campaign state
// (GET /api/campaign-state)
func (_ Unimplemented) GetCampaignState(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Reset campaign
// (POST /api/campaign/reset)
func (_ Unimplemented) ResetCampaign(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get attack flow
// (GET /api/flow)
func (_ Unimplemented) GetFlow(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Export attack flow
// (GET /api/flow/export)
func (_ Unimplemented) ExportAttackFlow(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Save attack flow
// (POST /api/flow/save)
func (_ Unimplemented) SaveFlow(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get attack graph
// (GET /api/graph)
func (_ Unimplemented) GetGraph(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get running pods
// (GET /api/pods/running)
func (_ Unimplemented) GetRunningPods(w http.ResponseWriter, r *http.Request, params GetRunningPodsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ExecuteAction operation middleware
func (siw *ServerInterfaceWrapper) ExecuteAction(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExecuteAction(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApplicableTTPs operation middleware
func (siw *ServerInterfaceWrapper) GetApplicableTTPs(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApplicableTTPsParams

	// ------------- Optional query parameter "targetId" -------------

	err = runtime.BindQueryParameter("form", true, false, "targetId", r.URL.Query(), &params.TargetId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "targetId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApplicableTTPs(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetArmory operation middleware
func (siw *ServerInterfaceWrapper) GetArmory(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetArmory(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCampaignState operation middleware
func (siw *ServerInterfaceWrapper) GetCampaignState(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCampaignState(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResetCampaign operation middleware
func (siw *ServerInterfaceWrapper) ResetCampaign(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResetCampaign(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetFlow operation middleware
func (siw *ServerInterfaceWrapper) GetFlow(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFlow(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ExportAttackFlow operation middleware
func (siw *ServerInterfaceWrapper) ExportAttackFlow(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExportAttackFlow(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SaveFlow operation middleware
func (siw *ServerInterfaceWrapper) SaveFlow(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SaveFlow(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGraph operation middleware
func (siw *ServerInterfaceWrapper) GetGraph(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGraph(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRunningPods operation middleware
func (siw *ServerInterfaceWrapper) GetRunningPods(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetRunningPodsParams

	// ------------- Optional query parameter "namespace" -------------

	err = runtime.BindQueryParameter("form", true, false, "namespace", r.URL.Query(), &params.Namespace)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRunningPods(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/action/execute", wrapper.ExecuteAction)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/applicable-ttps", wrapper.GetApplicableTTPs)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/armory", wrapper.GetArmory)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/campaign-state", wrapper.GetCampaignState)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/campaign/reset", wrapper.ResetCampaign)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/flow", wrapper.GetFlow)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/flow/export", wrapper.ExportAttackFlow)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/flow/save", wrapper.SaveFlow)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/graph", wrapper.GetGraph)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/pods/running", wrapper.GetRunningPods)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xaW4/buBX+KwTbhy2gGbtJWqR+m51cMMh2a9gG+rDNAy0dydxQpEJSnhgL//eCF90p",
	"W5rZye6bRyTP9Ts3cn7DscgLwYFrhVe/YRUfICf2553WJP7ygYlH81chRQFSU7BrkGTuB9WQ2x9/lZDi",
	"Ff7LoqG38MQW75MM8DnC+lQAXmEiJTmZv6UQ+meRwENiKPhVpSXlmVlWGorpTJy4Ww3FkJXhBV9LKiHB",
	"q1884chr0ZHjc31U7H+FWBtaLcoDQ+x262uCmS3nCBOZ2RMkSaimghO27lAaqD+QIxZ5TnjYVoYvAw3J",
	"nTbrqZA50XiFE6LhRtMccDQ8BN8gLjUk/+FBmjTMSuwVyCPZsx4CxhSo3V1IEUNSyjF/S1Al0zOJKk3k",
	"TLVVGceg2uT3QjAg3NInMgMdlLCHIprgCJPY+PLB/KxPNp6KLD66mnfM7mERYSOr0iQvcCNf19SNfdpK",
	"dz0fQu89yQtCM77VREMgkrmm1e8r0GxoDj5IYMSc7DovTE/LEqJRmuGIraVsswppa1PNQMkRJHOSwwgS",
	"HY/ZSihRyngM3xegFeFHoNmhC+KUCaIbAPMy34MMw9Bq0mLfYha0kpRCDs2UgCaUheMOqiOXg8JtC/J0",
	"qL+zAXOfJ0P2dSyF+D8/fV5LP9MjPxT0IZU/SlIcXqp4cpHMoGLK2+wS3FPbcZxcNj+9VRtwiJwckV8o",
	"nxmqZkEVJIaJCdtHimUUktoaKgBNk5F/giOw0fIrRU4VJOGyYhPYaXY+ccdGAPu72bAgErh+ggFbAoZs",
	"ua4ibmjQS73MiF5U/SRiwu4HJ9vVWwg2UY9KgpDgmx/v7tcgc6qUrwI9OBT0oxRlMdbG1KAfXfx5vPS4",
	"DTu7EOqKYzG2Yg9uBAsvH0HuJ+S2SjV/oKVPT/qerJVkHTmCxnXc8mrkmBdp8I2quT3iaETIPYkbP0/P",
	"pj18hLqXgdpbmuVkU7JAMCS+M5vWviagYkmLqj8JrGuIn9S9jAQeE1mD6FkEJaQggccwv6nX5chWks0k",
	"pqlmE6qD2+YZtJVuWzRyvgrB2k+C/Y4qBa5gwoj4zu+c4GBIU4jnxgCdXxNIPj0idrv12py4OPdNJ9dU",
	"jlDP4rx2PUrbiaaDqiuabN1Gi7ZY0zhsYIgPnH4t52H7QkVtu73m3OHTUr1j1dpbtY4jAH3XwLGH09dm",
	"JRnJJ5fhOBdZyiTCa15osuU5wqVkc5qTEeUdPkMhSkqmn6T6hQGyEizYpYRre7/dJk3+b630gVLJP6L1",
	"tgZ9RxnsviORIoJ2uzW6QY8H0AeQiGpEFQJO9gwSJCRKqLK/bbtX5m4er77Ui58HpcooRHkqhsw3kCAN",
	"JEek1CK3ozYiPEHE3rSh2F9ZoJxwktkARnfrB1zncrwh3H85gnQ9Gv777fJ2aS+oCuCkoHiFX98ub1/b",
	"8NAHa4MFKejCjW8Lfw1jESGUHkrpJ1ZvIHcKGUmRm/pu0e4A1fdHyhjaA/paQgmJ1aa650FEnXh8kIKL",
	"UrGTO5ZSTpjfYs67wK3JKKPzkRK03b6/xVYnSarxuDtLe3CA0j+K5OSaa659Q0+KgtHYnlz8qhyMXYxd",
	"nTv78/q5C1BT8l2/WgiuXCy9Wi5n8e9G4mjVH7ZT535wYidnY3N/iZaWjNmi8Wr56iVEM4lafRmbnqdK",
	"7UGTCtkgIkIF8ITyrAMfZNO+UpRnbRxdRM85wm9mOuYiMOwVT0CZB34kjCbIo9Hx/dfL821HIVE1BCK0",
	"LzVKCWXetErkgCQQw/Vs74HznMhTO9JdQJlFlymcsHsGN1q7t4gMdCif6VJyZfKEQvpANIoJN46wBEyy",
	"E0gfAKkCYpraDz6DPKSoukIyWVfkVGuXdSEv9ClCsk3aaEEY80fUMDF8BH1Xy2yOVL0BaJAKr37pS/7w",
	"zpQAI5ujidxAj34Qhevyo0oVK09fgr9hk+LxCn8tQZ6qArxq34U3zu3Hx+dnZo+pjWmgCxtgaFunC1TJ",
	"5PD75jvg11meC41SUfKkB86PoFEDxBYQvBNacJW5kKerKDX+I0dCWUPvh51tN1WEdnW7GdkiVnfi1tdD",
	"tDmWf3ZPDg3q5K5NV7UcN6p6JrloQhMwcSmlybN1t2KPokeqD6h6r7AmbF4sAgbsPs88046XzNdl9GTD",
	"dbUdGnAhQTnLhZuqjVm+YL+BjeyBSnj852k4KpGQVXjQb/zje1RcZ0xX4nq+ckuVbRs/pf49/yq8fS9u",
	"9jtM21dz19j6B4ABmO0/C7wghlv/kvD0yG/06lplAd8KIfVs41CO/v2w27xHd7vd/8rl8tU/7z8hIyPy",
	"93nD7t3waenyTItdhepIcfsuEHXKhjHq18Y9osjxwny2JUcYeEMLRFBK2TCRmO21uZ82L3XTh5kqh1J9",
	"oAyQWTKiqErE1DG+PPFbgp+DuedF567x/4eYkgi3rcxnFU7+uImjAy+LjyC4suphdnKR92TsQZcO7Wvo",
	"5XTo3n9fMB86Bs9NhZmn4o1TiEQtZMm5geg1GzGqtJkg/H5kDpuM2J12mkfagJU27uhaJFenlU/lHiQH",
	"Daoh2R5V/F2YslmAsWbT6KDSluwPnlTa7+VPn1i+S1L/4IZqLcx4KikcwTo+ALE2LhwlBfIY9u47OAIT",
	"hb3uc7uwv/vFB62L1WLBREzYQSi9ert8u8TGL4+wPwjxxb0d2qb+hgmSuKvXcN3YSZplICFBjwdwUHUn",
	"zQTe7uOQp/R7FYzmn7wmPvadn14Luir/11kJSYiBHgPXY29Cp6r06m2MCnIyFum52Y2A3lbVXiPp+f8B",
	"AAD//1BACZJdKgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
