// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for TTPStatus.
const (
	Disabled TTPStatus = "disabled"
	Enabled  TTPStatus = "enabled"
)

// AttackFlow defines model for AttackFlow.
type AttackFlow struct {
	Edges      []Edge       `json:"edges"`
	RootNodeId string       `json:"rootNodeId"`
	Steps      []AttackStep `json:"steps"`
}

type AttackStepStatus string

const (
	Unknown AttackStepStatus = "Unknown"
	Failed  AttackStepStatus = "Failed"
	Success AttackStepStatus = "Success"
	Ongoing AttackStepStatus = "Ongoing"
)

// AttackStep defines model for AttackStep.
type AttackStep struct {
	TTP         TTP               `json:"TTP"`
	Args        map[string]string `json:"args"`
	Command     string            `json:"command"`
	CompletedAt time.Time         `json:"completedAt"`
	Defense     *TTPDefense       `json:"defense,omitempty"`
	ExecutedOn  string            `json:"executedOn"`
	Id          string            `json:"id"`
	Observables []string          `json:"observables"`
	ProcedureId string            `json:"procedureId"`
	Results     []string          `json:"results"`
	StartedAt   time.Time        `json:"startedAt"`
	Status      AttackStepStatus `json:"status"`
	TargetId    string           `json:"targetId"`
}

// CampaignState defines model for CampaignState.
type CampaignState struct {
	Entities  map[string]map[string]interface{} `json:"entities"`
	Relations []map[string]interface{}          `json:"relations"`
}

// Edge defines model for Edge.
type Edge struct {
	Id       string                  `json:"id"`
	Name     string                  `json:"name"`
	Relation *map[string]interface{} `json:"relation,omitempty"`
	SourceId string                  `json:"sourceId"`
	TargetId string                  `json:"targetId"`
	Weight   *float32                `json:"weight,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Details *string `json:"details,omitempty"`
	Error   string  `json:"error"`
}

// ExecuteActionCmd defines model for ExecuteActionCmd.
type ExecuteActionCmd struct {
	ActionId    string             `json:"actionId"`
	Args        *map[string]string `json:"args,omitempty"`
	ProcedureId *string            `json:"procedureId,omitempty"`
	TargetId    string             `json:"targetId"`
}

// Graph defines model for Graph.
type Graph struct {
	Edges      []Edge `json:"edges"`
	Nodes      []Node `json:"nodes"`
	RootNodeId string `json:"rootNodeId"`
}

// K8sResource defines model for K8sResource.
type K8sResource struct {
	Id        string  `json:"id"`
	Kind      string  `json:"kind"`
	Name      string  `json:"name"`
	Namespace *string `json:"namespace,omitempty"`
}

// Node defines model for Node.
type Node struct {
	AccessLevel *string                 `json:"accessLevel,omitempty"`
	Compromised *bool                   `json:"compromised,omitempty"`
	Entity      *map[string]interface{} `json:"entity,omitempty"`
	EntityId    string                  `json:"entityId"`
	Id          string                  `json:"id"`
	Kind        string                  `json:"kind"`
	Name        string                  `json:"name"`
	Parent      *string                 `json:"parent,omitempty"`
}

// Procedure defines model for Procedure.
type Procedure struct {
	Command        string  `json:"command"`
	Id             string  `json:"id"`
	IsLocalCommand *bool   `json:"isLocalCommand,omitempty"`
	Tool           *string `json:"tool,omitempty"`
}

// RBACPermission defines model for RBACPermission.
type RBACPermission struct {
	ApiGroup     string `json:"apiGroup"`
	IsNamespaced bool   `json:"isNamespaced"`
	Resource     string `json:"resource"`
	ResourceName string `json:"resourceName"`
	ResourceType string `json:"resourceType"`
	Scope        string `json:"scope"`
	SourceRole   string `json:"sourceRole"`
	Verb         string `json:"verb"`
}

// Requirements defines model for Requirements.
type Requirements struct {
	AccessLevel     *string           `json:"accessLevel,omitempty"`
	Exists          *[]string         `json:"exists,omitempty"`
	Kind            *string           `json:"kind,omitempty"`
	RbacPermissions *[]RBACPermission `json:"rbacPermissions,omitempty"`
}

// SigmaRule defines model for SigmaRule.
type SigmaRule struct {
	Date        time.Time              `json:"date"`
	Description *string                `json:"description,omitempty"`
	Detection   map[string]interface{} `json:"detection"`
	Id          *string                `json:"id,omitempty"`
	Logsource   map[string]interface{} `json:"logsource"`
	References  *[]string              `json:"references,omitempty"`
	Status      *string                `json:"status,omitempty"`
	Tags        []string               `json:"tags"`
	Title       string                 `json:"title"`
}

// TTP defines model for TTP.
type TTP struct {
	Description string       `json:"description"`
	Effects     *[]string    `json:"effects,omitempty"`
	Id          string       `json:"id"`
	Name        string       `json:"name"`
	Params      []TTPParam   `json:"params"`
	Procedures  []Procedure  `json:"procedures"`
	Requires    Requirements `json:"requires"`

	// Status Status of a TTP - whether it is enabled or disabled
	Status     TTPStatus `json:"status"`
	Tactic     string    `json:"tactic"`
	Techniques []string  `json:"techniques"`
}

// TTPDefense defines model for TTPDefense.
type TTPDefense struct {
	D3efend     *string    `json:"d3efend,omitempty"`
	Description *string    `json:"description,omitempty"`
	Id          string     `json:"id"`
	Name        string     `json:"name"`
	Sigma       *SigmaRule `json:"sigma,omitempty"`
	Url         *string    `json:"url,omitempty"`
}

// TTPParam defines model for TTPParam.
type TTPParam struct {
	Default     string `json:"default"`
	Description string `json:"description"`
	Name        string `json:"name"`
	Required    bool   `json:"required"`
	Type        string `json:"type"`
}

// TTPStatus Status of a TTP - whether it is enabled or disabled
type TTPStatus string

// GetApplicableTTPsParams defines parameters for GetApplicableTTPs.
type GetApplicableTTPsParams struct {
	// TargetId ID of the target entity (optional, can be empty for all targets)
	TargetId *string `form:"targetId,omitempty" json:"targetId,omitempty"`
}

// GetArmoryParams defines parameters for GetArmory.
type GetArmoryParams struct {
	// Tactic Optional tactic to filter by (e.g., "Execution", "CredentialAccess")
	Tactic *string `form:"tactic,omitempty" json:"tactic,omitempty"`
}

// SaveFlowJSONBody defines parameters for SaveFlow.
type SaveFlowJSONBody struct {
	// Path File path to save the flow
	Path string `json:"path"`
}

// GetRunningPodsParams defines parameters for GetRunningPods.
type GetRunningPodsParams struct {
	// Namespace Kubernetes namespace (optional, defaults to all namespaces)
	Namespace *string `form:"namespace,omitempty" json:"namespace,omitempty"`
}

// ExecuteActionJSONRequestBody defines body for ExecuteAction for application/json ContentType.
type ExecuteActionJSONRequestBody = ExecuteActionCmd

// SaveFlowJSONRequestBody defines body for SaveFlow for application/json ContentType.
type SaveFlowJSONRequestBody SaveFlowJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Execute action
	// (POST /api/action/execute)
	ExecuteAction(w http.ResponseWriter, r *http.Request)
	// Get applicable TTPs for a target
	// (GET /api/applicable-ttps)
	GetApplicableTTPs(w http.ResponseWriter, r *http.Request, params GetApplicableTTPsParams)
	// Get armory
	// (GET /api/armory)
	GetArmory(w http.ResponseWriter, r *http.Request, params GetArmoryParams)
	// Get campaign state
	// (GET /api/campaign-state)
	GetCampaignState(w http.ResponseWriter, r *http.Request)
	// Reset campaign
	// (POST /api/campaign/reset)
	ResetCampaign(w http.ResponseWriter, r *http.Request)
	// Get attack flow
	// (GET /api/flow)
	GetFlow(w http.ResponseWriter, r *http.Request)
	// Export attack flow
	// (GET /api/flow/export)
	ExportAttackFlow(w http.ResponseWriter, r *http.Request)
	// Save attack flow
	// (POST /api/flow/save)
	SaveFlow(w http.ResponseWriter, r *http.Request)
	// Get attack graph
	// (GET /api/graph)
	GetGraph(w http.ResponseWriter, r *http.Request)
	// Get running pods
	// (GET /api/pods/running)
	GetRunningPods(w http.ResponseWriter, r *http.Request, params GetRunningPodsParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Execute action
// (POST /api/action/execute)
func (_ Unimplemented) ExecuteAction(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get applicable TTPs for a target
// (GET /api/applicable-ttps)
func (_ Unimplemented) GetApplicableTTPs(w http.ResponseWriter, r *http.Request, params GetApplicableTTPsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get armory
// (GET /api/armory)
func (_ Unimplemented) GetArmory(w http.ResponseWriter, r *http.Request, params GetArmoryParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get campaign state
// (GET /api/campaign-state)
func (_ Unimplemented) GetCampaignState(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Reset campaign
// (POST /api/campaign/reset)
func (_ Unimplemented) ResetCampaign(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get attack flow
// (GET /api/flow)
func (_ Unimplemented) GetFlow(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Export attack flow
// (GET /api/flow/export)
func (_ Unimplemented) ExportAttackFlow(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Save attack flow
// (POST /api/flow/save)
func (_ Unimplemented) SaveFlow(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get attack graph
// (GET /api/graph)
func (_ Unimplemented) GetGraph(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get running pods
// (GET /api/pods/running)
func (_ Unimplemented) GetRunningPods(w http.ResponseWriter, r *http.Request, params GetRunningPodsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ExecuteAction operation middleware
func (siw *ServerInterfaceWrapper) ExecuteAction(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExecuteAction(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApplicableTTPs operation middleware
func (siw *ServerInterfaceWrapper) GetApplicableTTPs(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApplicableTTPsParams

	// ------------- Optional query parameter "targetId" -------------

	err = runtime.BindQueryParameter("form", true, false, "targetId", r.URL.Query(), &params.TargetId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "targetId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApplicableTTPs(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetArmory operation middleware
func (siw *ServerInterfaceWrapper) GetArmory(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetArmoryParams

	// ------------- Optional query parameter "tactic" -------------

	err = runtime.BindQueryParameter("form", true, false, "tactic", r.URL.Query(), &params.Tactic)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tactic", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetArmory(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCampaignState operation middleware
func (siw *ServerInterfaceWrapper) GetCampaignState(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCampaignState(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResetCampaign operation middleware
func (siw *ServerInterfaceWrapper) ResetCampaign(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResetCampaign(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetFlow operation middleware
func (siw *ServerInterfaceWrapper) GetFlow(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFlow(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ExportAttackFlow operation middleware
func (siw *ServerInterfaceWrapper) ExportAttackFlow(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExportAttackFlow(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SaveFlow operation middleware
func (siw *ServerInterfaceWrapper) SaveFlow(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SaveFlow(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGraph operation middleware
func (siw *ServerInterfaceWrapper) GetGraph(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGraph(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRunningPods operation middleware
func (siw *ServerInterfaceWrapper) GetRunningPods(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetRunningPodsParams

	// ------------- Optional query parameter "namespace" -------------

	err = runtime.BindQueryParameter("form", true, false, "namespace", r.URL.Query(), &params.Namespace)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRunningPods(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/action/execute", wrapper.ExecuteAction)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/applicable-ttps", wrapper.GetApplicableTTPs)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/armory", wrapper.GetArmory)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/campaign-state", wrapper.GetCampaignState)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/campaign/reset", wrapper.ResetCampaign)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/flow", wrapper.GetFlow)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/flow/export", wrapper.ExportAttackFlow)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/flow/save", wrapper.SaveFlow)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/graph", wrapper.GetGraph)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/pods/running", wrapper.GetRunningPods)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RaW2/bOBb+KwR3HzqAEnvb7qLrt0x6QdDZThAb2IdpH2jpSOaUIlWScmoM/N8XvOhO",
	"2VIySXfeZJM81+/cKP2BY5EXggPXCq/+wCreQU7s45XWJP76nol786uQogCpKdg1SDL3QDXk9uHvElK8",
	"wn9bNPQWntjiXZIBPkZYHwrAK0ykJAfzWwqhP4kEbhJDwa8qLSnPzLLSUExn4sRdayiGrAwv+FZSCQle",
	"/eYJR16Ljhxf6qNi+zvE2tBqUR4YYrO5PSeY2XKMMJGZPUGShGoqOGG3HUoD9QdyxCLPCQ/byvBloCG5",
	"0mY9FTInGq9wQjRcaJoDjoaHEkiBK5igwFu/8xhh+A5xqSH5lQcFoWH5xFaB3JMt68FmTOsaI4UUMSSl",
	"HAOJBFUyPZOo0kTOtJUq4xhUm/xWCAaEW/pEZqCDEvagRxMcYRIbANyYx/pk497IgqqrecfsHksRNrIq",
	"TfICN/J1Td3Yp610Fy4hyF+TvCA042tNNATCn2taPZ/Bc0Nz8IcERszJrvPC9LQsIRqlGQ7zWso2q5C2",
	"Nj8NlBxBMic5jCDR8ZithBKljMfwfQJaEb4Hmu26IE6ZILoBMC/zLcgwDK0mLfYtZkErSSnk0EwJaEJZ",
	"OO6gOnI6KNy2IE+H+isbMNd5MmRfx1KI/+Nz7rn0Mz3yQ0EfUvmDJMXuqSouF8kMKqYmzq7bPbUdx8m1",
	"9uMbdQcOkZMj8ivlM0PVLKiCxDAxYftIsYxCUltDBaBpMvIvsAc2WrOlyKmCJFxWbAI7zM4n7tgIYP80",
	"GxZEAtcPMGBLwJAtb6uIGxr0VAM0ohdVv4iYsOvByXb1FoJN1KOSICT43c9X17cgc6qUrwI9OBT0gxRl",
	"MSLnpwqTicuqKSmZxquUMNU4uSW1bIVJqCuyi5/Gi5XbsLELoeY7FmMr9uCdYOHlPcjthGxYGcMfaOnT",
	"k74nayVZR46e/YLecczzatCZF6rwnaq5TeZoSMktiRugTE/HPYCF2p+B2mua5eSuZIFoSnxrN3VWULGk",
	"RdXgBNY1xA9qf0Yil4msAfgsghJSkMBjmD8V6HJkK8lmEtNUswnlxW3zDNpKty0aOV+FYO3nz35LdtpX",
	"kKYQz4UznV8fSD4d3JvN7a05cXIGnE6uqSKh/sU54HzAtXNGByBnNFm7jRY4saZx2MAQ7zj9Vs6D6Ynq",
	"2nZ7zbnDp6V6x6q1t2odR7D2trkx6EHulVlJRlLDaTjORZYyOe2cF5rEd4xwKdmcRmVEeYfPQLT5Uv0A",
	"1U8Mk5VgwY4lXLX7rTdpUnlrpQ+USv4Rrdc16DvKYPc/EikiaLO5RRfofgd6BxJRjahCwMmWQYKERAlV",
	"9tm2fmXuZvPqn3rxy6DqGIUoT8WQ+R0kSAPJESm1yO3YjQhPELFXdSj21xcoJ5xkNoDR1e0NrtMyviPc",
	"/7MH6fo1/I/L5eXSXlYVwElB8Qq/ulxevrLhoXfWBgtS0IUb5Rb+SsYiQig9lNJPr95A7hQykiI3AV6i",
	"zQ6q/+8pY2gL6FsJJSRWm+rOBxF14PFOCi5KxQ7uWEo5YX6LOe8CtyajjM57StB6/e4SW50kqUbl7lzt",
	"wQFK/yySg2u0ufbNPSkKRmN7cvG7cjB2MXZ2Bu3P7scuQE31dp1oIbhysfRyuZzFvxuJowV82Bkd+8GJ",
	"nZyNzf2FWloyZovGy+XLpxDNJGr1dWySniq1B00qZIOICBXAE8qzDnyQTftKUZ61cXQSPccIv57pmJPA",
	"sNc9AWVu+J4wmiCPRsf39dPzNWZQBcQ0pSbYfJxKH6XonijEhUapKHnihPr38whVpQaialxGaFtqlBLK",
	"vL+VyAFJIIbr0V5U5zmRh3b6cVFuFl36csJuGVxo7d6wZKBDSVaXkiuTvBTSO6JRTLhBhyVgMrBAumO6",
	"Kq3dpKi64zKlQORUa1cKIC/0IUKyTdpoQRjzR9QwW30AfVXLbI5UDQtokAqvfutLfvPW1CUjm3ehu3FA",
	"L0ThpoioUsXK05fgJzNQGjrfSpCHqitYtS/rG+f2g/bLI1Pa1G450BoOMLSucxiqZHq+oHKWbwVOB5wf",
	"QKMGiC0geCe04CpzIQ9nUWr8R/aEsobei43tgVWENnUPHNnKWo8H6qdL9KsHBTuglDINEm0PyLXPYSw6",
	"gc5gsKLqKZlgaai/gMvsMkKffYxSwT9j8/NaQmKwStiV9dxnPI5F397/hZE4BISzbO36qo+7UNV7qJMQ",
	"MAEfl1Ka4lW3gPYouqd6h6oXQhYCzSuhgIu7778eacdT5usyerDhutoODbiQoJzlwp3qnVk+Yb+BjeyB",
	"Snj8/9PFVSIhq/Cgifvnc7QxzpiuRPd85ZYq2zZ+Sv1XFmfh7Qccs99h2n7L4KYF/4ZlAGb7CccTYrj1",
	"ocjDI7/Rq2uVBXwvhNSzjUM5+s/N5u4dutpsPpfL5ct/XX9ERkbk7zuHI5Hh09LlkRY7C9WR4vwsEHXK",
	"hjHq18Y9osj+xNC7JnsYeEMLREz5GyYSs70298OG0G76MKP6UKr3lAEyS0YUVYmYOsanr1EswS/B3POk",
	"w+z4BydTEuG6lfmswsmPG+M68LL4CIIrq958Ty7ynow96NKhfd18Oh26F+xPmA8dg8emwsxT8cYpRKIW",
	"suTcQPScjRhV2kxAfj8yh01G7E5rzVvwgJXu3NFbkZydtj6WW5AcNKiGZHvU8heMymYBxppNo4NWW7If",
	"3N+2P0h4+MT1LEn9vbsU0MKM15LCHqzjAxBr48JRUiD3Ye++hT0wUdg7VLcL+wt1vNO6WC0WTMSE7YTS",
	"qzfLN0ts/HIP250QX927VdvUXzBBEnefHa4bG0mzDCQk6H4HDqruJKKq08chT+nPKhjNV3QTX4YeH14L",
	"uir/11kJSYiB7gN3jq9Dp6r06m2MCnIwFum52Q2p3lbVXiPp8X8BAAD///PqfJnzKwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
