use std::{env, fs, path::PathBuf};

use anyhow::{anyhow, Context, Result};
use serde_yaml::{Mapping, Value};

fn main() -> Result<()> {
    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").context("missing CARGO_MANIFEST_DIR")?);
    let spec_path = manifest_dir.join("../../src/api/openapi.yaml");
    println!("cargo:rerun-if-changed={}", spec_path.display());

    let spec_text = fs::read_to_string(&spec_path)
        .with_context(|| format!("failed to read OpenAPI spec at {}", spec_path.display()))?;
    let spec: Value = serde_yaml::from_str(&spec_text).context("failed to parse OpenAPI YAML")?;

    let paths = get_mapping(&spec, "paths")?;
    let endpoint = paths
        .get(Value::String("/api/pods/running".to_string()))
        .and_then(Value::as_mapping)
        .ok_or_else(|| anyhow!("OpenAPI path /api/pods/running not found"))?;
    let get_op = endpoint
        .get(Value::String("get".to_string()))
        .and_then(Value::as_mapping)
        .ok_or_else(|| anyhow!("GET operation for /api/pods/running not found"))?;

    let operation_id = get_op
        .get(Value::String("operationId".to_string()))
        .and_then(Value::as_str)
        .ok_or_else(|| anyhow!("operationId for /api/pods/running not found"))?;

    if operation_id != "getRunningPods" {
        return Err(anyhow!(
            "unexpected operationId for /api/pods/running: {}",
            operation_id
        ));
    }

    let components = get_mapping(&spec, "components")?;
    let schemas = components
        .get(Value::String("schemas".to_string()))
        .and_then(Value::as_mapping)
        .ok_or_else(|| anyhow!("components.schemas not found"))?;

    ensure_schema_has_fields(schemas, "K8sResource", &["id", "name", "kind"])?;
    ensure_schema_has_fields(schemas, "Error", &["error"])?;

    let out_dir = PathBuf::from(env::var("OUT_DIR").context("missing OUT_DIR")?);
    let out_file = out_dir.join("openapi_generated.rs");

    let generated = r#"// @generated by build.rs from src/api/openapi.yaml
use axum::{
    extract::{Query, State},
    http::StatusCode,
    response::{IntoResponse, Response},
    routing::get,
    Json, Router,
};
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct K8sResource {
    pub id: String,
    pub name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
    pub kind: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub phase: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ready: Option<bool>,
    #[serde(rename = "stateReason", skip_serializing_if = "Option::is_none")]
    pub state_reason: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ErrorResponse {
    pub error: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub details: Option<String>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct GetRunningPodsParams {
    pub namespace: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CampaignStatePayload {
    pub entities: std::collections::HashMap<String, std::collections::HashMap<String, String>>,
    pub relations: Vec<std::collections::HashMap<String, String>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GraphPayload {
    #[serde(rename = "rootNodeId")]
    pub root_node_id: String,
    pub nodes: Vec<GraphNodePayload>,
    pub edges: Vec<GraphEdgePayload>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GraphNodePayload {
    pub id: String,
    #[serde(rename = "entityId")]
    pub entity_id: String,
    pub kind: String,
    pub name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parent: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub entity: Option<std::collections::HashMap<String, serde_json::Value>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GraphEdgePayload {
    pub id: String,
    #[serde(rename = "sourceId")]
    pub source_id: String,
    #[serde(rename = "targetId")]
    pub target_id: String,
    pub name: String,
}

#[derive(Debug)]
pub struct ApiError {
    pub status: StatusCode,
    pub body: ErrorResponse,
}

impl ApiError {
    pub fn internal(msg: impl Into<String>) -> Self {
        Self {
            status: StatusCode::INTERNAL_SERVER_ERROR,
            body: ErrorResponse {
                error: msg.into(),
                details: None,
            },
        }
    }
}

impl IntoResponse for ApiError {
    fn into_response(self) -> Response {
        (self.status, Json(self.body)).into_response()
    }
}

#[async_trait::async_trait]
pub trait ApiService: Clone + Send + Sync + 'static {
    async fn get_running_pods(
        &self,
        params: GetRunningPodsParams,
    ) -> Result<Vec<K8sResource>, ApiError>;

    async fn get_campaign(&self) -> Result<campaign::Campaign, ApiError>;
}

pub fn router<S: ApiService>(service: S) -> Router {
    Router::new()
        .route("/api/pods/running", get(get_running_pods_handler::<S>))
        .with_state(service)
}

async fn get_running_pods_handler<S: ApiService>(
    State(service): State<S>,
    Query(params): Query<GetRunningPodsParams>,
) -> Result<Json<Vec<K8sResource>>, ApiError> {
    let pods = service.get_running_pods(params).await?;
    Ok(Json(pods))
}
"#;

    fs::write(&out_file, generated)
        .with_context(|| format!("failed to write generated file {}", out_file.display()))?;

    Ok(())
}

fn get_mapping<'a>(v: &'a Value, key: &str) -> Result<&'a Mapping> {
    v.as_mapping()
        .and_then(|m| m.get(Value::String(key.to_string())))
        .and_then(Value::as_mapping)
        .ok_or_else(|| anyhow!("missing mapping key '{}'", key))
}

fn ensure_schema_has_fields(
    schemas: &Mapping,
    schema_name: &str,
    required_fields: &[&str],
) -> Result<()> {
    let schema = schemas
        .get(Value::String(schema_name.to_string()))
        .and_then(Value::as_mapping)
        .ok_or_else(|| anyhow!("schema '{}' not found", schema_name))?;

    let properties = schema
        .get(Value::String("properties".to_string()))
        .and_then(Value::as_mapping)
        .ok_or_else(|| anyhow!("schema '{}' missing properties", schema_name))?;

    for field in required_fields {
        if !properties.contains_key(Value::String((*field).to_string())) {
            return Err(anyhow!(
                "schema '{}' missing expected field '{}'",
                schema_name,
                field
            ));
        }
    }

    Ok(())
}
