use std::{collections::HashSet, env, fs, path::PathBuf};

use anyhow::{anyhow, Context, Result};
use serde_yaml::{Mapping, Value};

fn main() -> Result<()> {
    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").context("missing CARGO_MANIFEST_DIR")?);
    let spec_path = manifest_dir.join("../../src/api/openapi.yaml");
    println!("cargo:rerun-if-changed={}", spec_path.display());

    let spec_text = fs::read_to_string(&spec_path)
        .with_context(|| format!("failed to read OpenAPI spec at {}", spec_path.display()))?;
    let spec: Value = serde_yaml::from_str(&spec_text).context("failed to parse OpenAPI YAML")?;

    let paths = get_mapping(&spec, "paths")?;
    let endpoint = paths
        .get(Value::String("/api/pods/running".to_string()))
        .and_then(Value::as_mapping)
        .ok_or_else(|| anyhow!("OpenAPI path /api/pods/running not found"))?;
    let get_op = endpoint
        .get(Value::String("get".to_string()))
        .and_then(Value::as_mapping)
        .ok_or_else(|| anyhow!("GET operation for /api/pods/running not found"))?;

    let operation_id = get_op
        .get(Value::String("operationId".to_string()))
        .and_then(Value::as_str)
        .ok_or_else(|| anyhow!("operationId for /api/pods/running not found"))?;

    if operation_id != "getRunningPods" {
        return Err(anyhow!(
            "unexpected operationId for /api/pods/running: {}",
            operation_id
        ));
    }

    let components = get_mapping(&spec, "components")?;
    let schemas = components
        .get(Value::String("schemas".to_string()))
        .and_then(Value::as_mapping)
        .ok_or_else(|| anyhow!("components.schemas not found"))?;

    ensure_schema_has_fields(schemas, "K8sResource", &["id", "name", "kind"])?;
    ensure_schema_has_fields(schemas, "Error", &["error"])?;

    let mut generated = String::new();
    generated.push_str("// @generated by build.rs from src/api/openapi.yaml\n");
    generated.push_str(
        "use axum::{\n    extract::{Query, State},\n    http::StatusCode,\n    response::{IntoResponse, Response},\n    routing::get,\n    Json, Router,\n};\n",
    );
    generated.push_str("use serde::{Deserialize, Serialize};\n\n");

    generated.push_str(&generate_query_params(paths, "/api/pods/running", "get", "GetRunningPodsParams")?);
    generated.push('\n');
    generated.push_str(&generate_query_params(paths, "/api/armory", "get", "GetArmoryParams")?);
    generated.push('\n');

    for schema_name in ["K8sResource", "Error", "CampaignState", "Graph", "Node", "Edge"] {
        generated.push_str(&generate_object_schema_struct(schemas, schema_name)?);
        generated.push('\n');
    }

    generated.push_str(
        r#"
#[derive(Debug)]
pub struct ApiError {
    pub status: StatusCode,
    pub body: ErrorResponse,
}

impl ApiError {
    pub fn internal(msg: impl Into<String>) -> Self {
        Self {
            status: StatusCode::INTERNAL_SERVER_ERROR,
            body: ErrorResponse {
                error: msg.into(),
                details: None,
            },
        }
    }
}

impl IntoResponse for ApiError {
    fn into_response(self) -> Response {
        (self.status, Json(self.body)).into_response()
    }
}

#[async_trait::async_trait]
pub trait ApiService: Clone + Send + Sync + 'static {
    async fn get_running_pods(
        &self,
        params: GetRunningPodsParams,
    ) -> Result<Vec<K8sResource>, ApiError>;

    async fn get_armory(&self, params: GetArmoryParams) -> Result<Vec<armory::Ttp>, ApiError>;

    async fn execute_action(
        &self,
        cmd: campaign::ExecuteActionRequest,
    ) -> Result<campaign::ExecuteActionResult, ApiError>;

    async fn get_campaign(&self) -> Result<campaign::Campaign, ApiError>;

    async fn reset_campaign(&self) -> Result<(), ApiError>;
}

pub fn router<S: ApiService>(service: S) -> Router {
    Router::new()
        .route("/api/pods/running", get(get_running_pods_handler::<S>))
        .with_state(service)
}

async fn get_running_pods_handler<S: ApiService>(
    State(service): State<S>,
    Query(params): Query<GetRunningPodsParams>,
) -> Result<Json<Vec<K8sResource>>, ApiError> {
    let pods = service.get_running_pods(params).await?;
    Ok(Json(pods))
}
"#,
    );

    let out_dir = PathBuf::from(env::var("OUT_DIR").context("missing OUT_DIR")?);
    let out_file = out_dir.join("openapi_generated.rs");
    fs::write(&out_file, generated)
        .with_context(|| format!("failed to write generated file {}", out_file.display()))?;

    Ok(())
}

fn generate_query_params(
    paths: &Mapping,
    path_key: &str,
    method: &str,
    struct_name: &str,
) -> Result<String> {
    let op = paths
        .get(Value::String(path_key.to_string()))
        .and_then(Value::as_mapping)
        .and_then(|p| p.get(Value::String(method.to_string())))
        .and_then(Value::as_mapping)
        .ok_or_else(|| anyhow!("missing operation {} {}", method.to_uppercase(), path_key))?;

    let params = op
        .get(Value::String("parameters".to_string()))
        .and_then(Value::as_sequence)
        .cloned()
        .unwrap_or_default();

    let mut out = String::new();
    out.push_str("#[derive(Debug, Clone, Deserialize)]\n");
    out.push_str(&format!("pub struct {} {{\n", struct_name));

    for p in params {
        let Some(pm) = p.as_mapping() else {
            continue;
        };

        let in_query = pm
            .get(Value::String("in".to_string()))
            .and_then(Value::as_str)
            .map(|s| s == "query")
            .unwrap_or(false);
        if !in_query {
            continue;
        }

        let name = pm
            .get(Value::String("name".to_string()))
            .and_then(Value::as_str)
            .ok_or_else(|| anyhow!("query parameter without name in {} {}", method, path_key))?;

        let required = pm
            .get(Value::String("required".to_string()))
            .and_then(Value::as_bool)
            .unwrap_or(false);

        let schema = pm
            .get(Value::String("schema".to_string()))
            .and_then(Value::as_mapping)
            .ok_or_else(|| anyhow!("query parameter '{}' without schema", name))?;

        let base_ty = rust_type_for_schema_inline(schema)?;
        let field_ty = if required {
            base_ty
        } else {
            format!("Option<{}>", base_ty)
        };

        let rust_name = to_snake_case(name);
        if rust_name != name {
            out.push_str(&format!("    #[serde(rename = \"{}\")]\n", name));
        }
        out.push_str(&format!("    pub {}: {},\n", rust_name, field_ty));
    }

    out.push_str("}\n");
    Ok(out)
}

fn generate_object_schema_struct(schemas: &Mapping, schema_name: &str) -> Result<String> {
    let schema = schemas
        .get(Value::String(schema_name.to_string()))
        .and_then(Value::as_mapping)
        .ok_or_else(|| anyhow!("schema '{}' not found", schema_name))?;

    let ty = schema
        .get(Value::String("type".to_string()))
        .and_then(Value::as_str)
        .unwrap_or("object");

    if ty != "object" {
        return Err(anyhow!(
            "schema '{}' is not an object (type='{}')",
            schema_name,
            ty
        ));
    }

    let rust_struct = rust_type_name(schema_name);

    let required: HashSet<String> = schema
        .get(Value::String("required".to_string()))
        .and_then(Value::as_sequence)
        .map(|seq| {
            seq.iter()
                .filter_map(Value::as_str)
                .map(ToOwned::to_owned)
                .collect()
        })
        .unwrap_or_default();

    let properties = schema
        .get(Value::String("properties".to_string()))
        .and_then(Value::as_mapping)
        .ok_or_else(|| anyhow!("schema '{}' missing properties", schema_name))?;

    let mut out = String::new();
    out.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
    out.push_str(&format!("pub struct {} {{\n", rust_struct));

    for (k, v) in properties {
        let Some(json_name) = k.as_str() else {
            continue;
        };
        let Some(prop_schema) = v.as_mapping() else {
            continue;
        };

        let mut field_ty = rust_type_for_schema_inline(prop_schema)?;
        let is_required = required.contains(json_name);
        let rust_field = to_snake_case(json_name);

        if !is_required {
            field_ty = format!("Option<{}>", field_ty);
        }

        if rust_field != json_name {
            out.push_str(&format!("    #[serde(rename = \"{}\"", json_name));
            if !is_required {
                out.push_str(", skip_serializing_if = \"Option::is_none\"");
            }
            out.push_str(")]\n");
        } else if !is_required {
            out.push_str("    #[serde(skip_serializing_if = \"Option::is_none\")]\n");
        }

        out.push_str(&format!("    pub {}: {},\n", rust_field, field_ty));
    }

    out.push_str("}\n");
    Ok(out)
}

fn rust_type_for_schema_inline(schema: &Mapping) -> Result<String> {
    if let Some(r) = schema
        .get(Value::String("$ref".to_string()))
        .and_then(Value::as_str)
    {
        let ref_name = r
            .rsplit('/')
            .next()
            .ok_or_else(|| anyhow!("invalid $ref '{}': missing tail", r))?;
        return Ok(rust_type_name(ref_name));
    }

    let ty = schema
        .get(Value::String("type".to_string()))
        .and_then(Value::as_str)
        .unwrap_or("object");

    match ty {
        "string" => Ok("String".to_string()),
        "boolean" => Ok("bool".to_string()),
        "integer" => Ok("i64".to_string()),
        "number" => Ok("f64".to_string()),
        "array" => {
            let items = schema
                .get(Value::String("items".to_string()))
                .and_then(Value::as_mapping)
                .ok_or_else(|| anyhow!("array schema missing items"))?;
            Ok(format!("Vec<{}>", rust_type_for_schema_inline(items)?))
        }
        "object" => {
            if let Some(additional) = schema.get(Value::String("additionalProperties".to_string()))
            {
                return match additional {
                    Value::Bool(true) => {
                        Ok("std::collections::HashMap<String, serde_json::Value>".to_string())
                    }
                    Value::Bool(false) => Ok("serde_json::Value".to_string()),
                    Value::Mapping(m) => Ok(format!(
                        "std::collections::HashMap<String, {}>",
                        rust_type_for_schema_inline(m)?
                    )),
                    _ => Ok("std::collections::HashMap<String, serde_json::Value>".to_string()),
                };
            }

            // OpenAPI object without additionalProperties/properties maps best to dynamic JSON map.
            Ok("std::collections::HashMap<String, serde_json::Value>".to_string())
        }
        _ => Ok("serde_json::Value".to_string()),
    }
}

fn rust_type_name(schema_name: &str) -> String {
    match schema_name {
        // Preserve existing API naming conventions in Rust types.
        "Error" => "ErrorResponse".to_string(),
        "Node" => "GraphNode".to_string(),
        "Edge" => "GraphEdge".to_string(),
        other => other.to_string(),
    }
}

fn to_snake_case(input: &str) -> String {
    let mut out = String::with_capacity(input.len() + 4);
    let mut prev_is_lower_or_digit = false;

    for ch in input.chars() {
        if ch.is_ascii_alphanumeric() {
            if ch.is_ascii_uppercase() {
                if prev_is_lower_or_digit {
                    out.push('_');
                }
                out.push(ch.to_ascii_lowercase());
                prev_is_lower_or_digit = false;
            } else {
                out.push(ch);
                prev_is_lower_or_digit = ch.is_ascii_lowercase() || ch.is_ascii_digit();
            }
        } else {
            if !out.ends_with('_') {
                out.push('_');
            }
            prev_is_lower_or_digit = false;
        }
    }

    out.trim_matches('_').to_string()
}

fn get_mapping<'a>(v: &'a Value, key: &str) -> Result<&'a Mapping> {
    v.as_mapping()
        .and_then(|m| m.get(Value::String(key.to_string())))
        .and_then(Value::as_mapping)
        .ok_or_else(|| anyhow!("missing mapping key '{}'", key))
}

fn ensure_schema_has_fields(schemas: &Mapping, schema_name: &str, required_fields: &[&str]) -> Result<()> {
    let schema = schemas
        .get(Value::String(schema_name.to_string()))
        .and_then(Value::as_mapping)
        .ok_or_else(|| anyhow!("schema '{}' not found", schema_name))?;

    let properties = schema
        .get(Value::String("properties".to_string()))
        .and_then(Value::as_mapping)
        .ok_or_else(|| anyhow!("schema '{}' missing properties", schema_name))?;

    for field in required_fields {
        if !properties.contains_key(Value::String((*field).to_string())) {
            return Err(anyhow!(
                "schema '{}' missing expected field '{}'",
                schema_name,
                field
            ));
        }
    }

    Ok(())
}
