name: Check Kubeconfig Permissions
description: Query the Kubernetes API for permissions granted to the active kubeconfig identity
tactic: Discovery
techniques: ["Permission Groups Discovery", "T1069.003"]
parameters:
  NS:
    type: Namespace
    description: Namespace in which namespaced permissions should be evaluated
    default: default
preconditions:
  kind: K8sCredential
procedures:
  - key: k8s-client
    command: k8sSelfSubjectRulesReview(${NS})
    isLocal: true
effects:
  - k8s.SelfSubjectRulesReview
references: []
