name: Check Kubeconfig Permissions
description: Query the Kubernetes API for permissions granted to the selected kubeconfig identity
tactic: Discovery
techniques: ["Permission Groups Discovery", "T1069.003"]
parameters:
  K8S_AUTH:
    type: K8sAuth
    description: the selected kubeconfig identity
  NS:
    type: Namespace
    description: Namespace in which namespaced permissions should be evaluated
    default: default
preconditions:
  kind: K8sCredential
procedures:
  - key: k8s-client
    command: k8sSelfSubjectRulesReview(${NS})
    isLocal: true
    operation:
      type: self-subject-rules-review
      namespace: ${NS}
  - key: source-kubeconfig
    command: chroot ${KUBECONFIG_ROOT} kubectl ${K8S_AUTH} auth can-i --list -n ${NS}
    sourceKubeconfig: true
effects:
  - k8s.SelfSubjectRulesReview
references: []
