name: Get Deployments
description: Get a list of deployments via the API server
tactic: Discovery
techniques: [ "Container and Resource Discovery", T1613 ]
preconditions:
  # accessLevel: user-read
  rbac:
    - verb: get
      resource: deployments
parameters:
  K8S_AUTH:
    type: K8sAuth
    description: the Kubernetes identity selected by Authenticate As
  NS:
    type: Namespace
    description: specify the namespace to get pods from
    default: ${NS}
  ALL_NS:
    type: bool
    description: get pods from all namespaces or just the current one
    default: false
procedures:
  - key: kubectl
    command: >-
      kubectl get deployments ${K8S_AUTH} -n=${NS} -A=${ALL_NS}
      --output=json
  - key: k8s-request
    k8s_request:
      authentication: ${K8S_AUTH}
      api_server: ${API_SERVER}
      api: /apis/apps/v1
      resource: deployments
      namespace: ${NS}
      cluster_scoped: ${ALL_NS}
      query: limit=500
      ca_path: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
effects:
  - k8s.deploymentList
# defend: {}
references:
