id: get-ingresses
name: Get Ingresses via API Server
description: Enumerate Kubernetes Ingress resources to map externally exposed HTTP/HTTPS entry points, identify backend services, and discover TLS secret references
tactic: Discovery
techniques: ["Container and Resource Discovery", T1613]
preconditions:
  rbac:
    - verb: list
      resource: ingresses
parameters:
  TOKEN:
    type: ServiceAccount
    description: the ServiceAccount token used to authorize this request
    optional: true
    default: ""
  NS:
    type: Namespace
    description: namespace to enumerate
    default: ${NS}
  ALL_NS:
    type: bool
    description: enumerate ingresses across all namespaces
    default: false
procedures:
  - key: kubectl
    command: >-
      kubectl get ingresses --token=${TOKEN} -n=${NS} -A=${ALL_NS} --output=json
  - key: curl
    command: >-
      curl -XGET -k
      -H "Accept: application/json"
      -H "User-Agent: kubectl/v1.35.0 (linux/amd64) kubernetes/6fc0a69"
      -H "Authorization: Bearer ${TOKEN}"
      --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      {% if ALL_NS %}
      '${API_SERVER}/apis/networking.k8s.io/v1/ingresses?limit=500'
      {% else %}
      '${API_SERVER}/apis/networking.k8s.io/v1/namespaces/${NS}/ingresses?limit=500'
      {% endif %}
effects:
  - k8s.ingresslist
references:
  - https://kubernetes.io/docs/concepts/services-networking/ingress/
  - https://attack.mitre.org/techniques/T1613/
