name: Read Environment variables
description: Read environment variables from a target
tactic: Discovery
techniques:
  ["Container and Resource Discovery", "Network Service Discovery", T1613]
preconditions:
  kind: System
  accessLevel: user-read
procedures:
  - key: shell
    command: env
  - key: read /proc/*/environ
    tool: cat
    command: cat /proc/self/environ
effects: ["sys.envVar"]
# effects:
# defend: {}
# references:
