[package]
name = "k8s"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
k8s-openapi = { version = "0.27", features = ["v1_32"] }
kube = { version = "3.1", default-features = true, features = ["ws"] }
http = "1"
regex = "1"
serde = { workspace = true }
serde_json = "1"
serde_yaml = "0.9"
secrecy = "0.10.2"
tokio = { version = "1", features = ["io-util", "process", "rt", "time"] }
tracing = "0.1"
