// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for AttackStepStatus.
const (
	Failed  AttackStepStatus = "Failed"
	Ongoing AttackStepStatus = "Ongoing"
	Success AttackStepStatus = "Success"
	Unknown AttackStepStatus = "Unknown"
)

// Valid indicates whether the value is a known member of the AttackStepStatus enum.
func (e AttackStepStatus) Valid() bool {
	switch e {
	case Failed:
		return true
	case Ongoing:
		return true
	case Success:
		return true
	case Unknown:
		return true
	default:
		return false
	}
}

// Defines values for TTPStatus.
const (
	Disabled TTPStatus = "disabled"
	Enabled  TTPStatus = "enabled"
)

// Valid indicates whether the value is a known member of the TTPStatus enum.
func (e TTPStatus) Valid() bool {
	switch e {
	case Disabled:
		return true
	case Enabled:
		return true
	default:
		return false
	}
}

// AttackFlow defines model for AttackFlow.
type AttackFlow struct {
	Edges      []Edge       `json:"edges"`
	RootNodeId string       `json:"rootNodeId"`
	Steps      []AttackStep `json:"steps"`
}

// AttackStep defines model for AttackStep.
type AttackStep struct {
	TTP         TTP               `json:"TTP"`
	Args        map[string]string `json:"args"`
	Command     string            `json:"command"`
	CompletedAt time.Time         `json:"completedAt"`
	Defense     *TTPDefense       `json:"defense,omitempty"`
	ExecutedOn  string            `json:"executedOn"`
	Id          string            `json:"id"`
	Observables []string          `json:"observables"`
	ProcedureId string            `json:"procedureId"`
	Results     []string          `json:"results"`
	StartedAt   time.Time         `json:"startedAt"`
	Status      AttackStepStatus  `json:"status"`
	TargetId    string            `json:"targetId"`
}

// AttackStepStatus defines model for AttackStep.Status.
type AttackStepStatus string

// CampaignState defines model for CampaignState.
type CampaignState struct {
	Entities  map[string]map[string]interface{} `json:"entities"`
	Relations []map[string]interface{}          `json:"relations"`
}

// Edge defines model for Edge.
type Edge struct {
	Id       string                  `json:"id"`
	Name     string                  `json:"name"`
	Relation *map[string]interface{} `json:"relation,omitempty"`
	SourceId string                  `json:"sourceId"`
	TargetId string                  `json:"targetId"`
	Weight   *float32                `json:"weight,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Details *string `json:"details,omitempty"`
	Error   string  `json:"error"`
}

// ExecuteActionCmd defines model for ExecuteActionCmd.
type ExecuteActionCmd struct {
	ActionId     string             `json:"actionId"`
	Args         *map[string]string `json:"args,omitempty"`
	ExecSystemId *string            `json:"execSystemId,omitempty"`
	ProcedureId  *string            `json:"procedureId,omitempty"`
	TargetId     string             `json:"targetId"`
}

// Graph defines model for Graph.
type Graph struct {
	Edges      []Edge `json:"edges"`
	Nodes      []Node `json:"nodes"`
	RootNodeId string `json:"rootNodeId"`
}

// K8sResource defines model for K8sResource.
type K8sResource struct {
	Id        string  `json:"id"`
	Kind      string  `json:"kind"`
	Name      string  `json:"name"`
	Namespace *string `json:"namespace,omitempty"`

	// Phase Pod phase (Running, Pending, Succeeded, Failed, Unknown)
	Phase *string `json:"phase,omitempty"`

	// Ready Whether all containers in the pod are ready
	Ready *bool `json:"ready,omitempty"`

	// StateReason Container-level state reason (e.g. CrashLoopBackOff, ImagePullBackOff)
	StateReason *string `json:"stateReason,omitempty"`
}

// Node defines model for Node.
type Node struct {
	AccessLevel *string                 `json:"accessLevel,omitempty"`
	Compromised *bool                   `json:"compromised,omitempty"`
	Entity      *map[string]interface{} `json:"entity,omitempty"`
	EntityId    string                  `json:"entityId"`
	Id          string                  `json:"id"`
	IsRunning   *bool                   `json:"isRunning,omitempty"`
	Kind        string                  `json:"kind"`
	Name        string                  `json:"name"`
	Parent      *string                 `json:"parent,omitempty"`
}

// Procedure defines model for Procedure.
type Procedure struct {
	Command        string  `json:"command"`
	Id             string  `json:"id"`
	IsLocalCommand *bool   `json:"isLocalCommand,omitempty"`
	Tool           *string `json:"tool,omitempty"`
}

// RBACPermission defines model for RBACPermission.
type RBACPermission struct {
	ApiGroup     string `json:"apiGroup"`
	IsNamespaced bool   `json:"isNamespaced"`
	Resource     string `json:"resource"`
	ResourceName string `json:"resourceName"`
	ResourceType string `json:"resourceType"`
	Scope        string `json:"scope"`
	SourceRole   string `json:"sourceRole"`
	Verb         string `json:"verb"`
}

// Requirements defines model for Requirements.
type Requirements struct {
	AccessLevel     *string           `json:"accessLevel,omitempty"`
	Exists          *[]string         `json:"exists,omitempty"`
	Kind            *string           `json:"kind,omitempty"`
	RbacPermissions *[]RBACPermission `json:"rbacPermissions,omitempty"`
}

// SigmaRule defines model for SigmaRule.
type SigmaRule struct {
	Date        time.Time              `json:"date"`
	Description *string                `json:"description,omitempty"`
	Detection   map[string]interface{} `json:"detection"`
	Id          *string                `json:"id,omitempty"`
	Logsource   map[string]interface{} `json:"logsource"`
	References  *[]string              `json:"references,omitempty"`
	Status      *string                `json:"status,omitempty"`
	Tags        []string               `json:"tags"`
	Title       string                 `json:"title"`
}

// TTP defines model for TTP.
type TTP struct {
	Description string       `json:"description"`
	Effects     *[]string    `json:"effects,omitempty"`
	Id          string       `json:"id"`
	Name        string       `json:"name"`
	Params      []TTPParam   `json:"params"`
	Procedures  []Procedure  `json:"procedures"`
	Requires    Requirements `json:"requires"`

	// Status Status of a TTP - whether it is enabled or disabled
	Status     TTPStatus `json:"status"`
	Tactic     string    `json:"tactic"`
	Techniques []string  `json:"techniques"`
}

// TTPDefense defines model for TTPDefense.
type TTPDefense struct {
	D3efend     *string    `json:"d3efend,omitempty"`
	Description *string    `json:"description,omitempty"`
	Id          string     `json:"id"`
	Name        string     `json:"name"`
	Sigma       *SigmaRule `json:"sigma,omitempty"`
	Url         *string    `json:"url,omitempty"`
}

// TTPParam defines model for TTPParam.
type TTPParam struct {
	Default     string `json:"default"`
	Description string `json:"description"`
	Name        string `json:"name"`
	Required    bool   `json:"required"`
	Type        string `json:"type"`
}

// TTPStatus Status of a TTP - whether it is enabled or disabled
type TTPStatus string

// GetApplicableTTPsParams defines parameters for GetApplicableTTPs.
type GetApplicableTTPsParams struct {
	// TargetId ID of the target entity (optional, can be empty for all targets)
	TargetId *string `form:"targetId,omitempty" json:"targetId,omitempty"`
}

// GetArmoryParams defines parameters for GetArmory.
type GetArmoryParams struct {
	// Tactic Optional tactic to filter by (e.g., "Execution", "CredentialAccess")
	Tactic *string `form:"tactic,omitempty" json:"tactic,omitempty"`
}

// GetFileContentParams defines parameters for GetFileContent.
type GetFileContentParams struct {
	// Path The file path to retrieve content for
	Path string `form:"path" json:"path"`
}

// SaveFlowJSONBody defines parameters for SaveFlow.
type SaveFlowJSONBody struct {
	// Path File path to save the flow
	Path string `json:"path"`
}

// GetRunningPodsParams defines parameters for GetRunningPods.
type GetRunningPodsParams struct {
	// Namespace Kubernetes namespace (optional, defaults to all namespaces)
	Namespace *string `form:"namespace,omitempty" json:"namespace,omitempty"`
}

// StartPodWatchParams defines parameters for StartPodWatch.
type StartPodWatchParams struct {
	// Namespace Kubernetes namespace to watch (optional, defaults to all namespaces)
	Namespace *string `form:"namespace,omitempty" json:"namespace,omitempty"`
}

// ExecuteActionJSONRequestBody defines body for ExecuteAction for application/json ContentType.
type ExecuteActionJSONRequestBody = ExecuteActionCmd

// SaveFlowJSONRequestBody defines body for SaveFlow for application/json ContentType.
type SaveFlowJSONRequestBody SaveFlowJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Execute action
	// (POST /api/action/execute)
	ExecuteAction(w http.ResponseWriter, r *http.Request)
	// Get applicable TTPs for a target
	// (GET /api/applicable-ttps)
	GetApplicableTTPs(w http.ResponseWriter, r *http.Request, params GetApplicableTTPsParams)
	// Get armory
	// (GET /api/armory)
	GetArmory(w http.ResponseWriter, r *http.Request, params GetArmoryParams)
	// Get campaign state
	// (GET /api/campaign-state)
	GetCampaignState(w http.ResponseWriter, r *http.Request)
	// Reset campaign
	// (POST /api/campaign/reset)
	ResetCampaign(w http.ResponseWriter, r *http.Request)
	// Get file content
	// (GET /api/files)
	GetFileContent(w http.ResponseWriter, r *http.Request, params GetFileContentParams)
	// Get attack flow
	// (GET /api/flow)
	GetFlow(w http.ResponseWriter, r *http.Request)
	// Export attack flow
	// (GET /api/flow/export)
	ExportAttackFlow(w http.ResponseWriter, r *http.Request)
	// Save attack flow
	// (POST /api/flow/save)
	SaveFlow(w http.ResponseWriter, r *http.Request)
	// Get attack graph
	// (GET /api/graph)
	GetGraph(w http.ResponseWriter, r *http.Request)
	// Get running pods
	// (GET /api/pods/running)
	GetRunningPods(w http.ResponseWriter, r *http.Request, params GetRunningPodsParams)
	// Stop watching pods
	// (DELETE /api/pods/watch)
	StopPodWatch(w http.ResponseWriter, r *http.Request)
	// Start watching pods
	// (POST /api/pods/watch)
	StartPodWatch(w http.ResponseWriter, r *http.Request, params StartPodWatchParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Execute action
// (POST /api/action/execute)
func (_ Unimplemented) ExecuteAction(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get applicable TTPs for a target
// (GET /api/applicable-ttps)
func (_ Unimplemented) GetApplicableTTPs(w http.ResponseWriter, r *http.Request, params GetApplicableTTPsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get armory
// (GET /api/armory)
func (_ Unimplemented) GetArmory(w http.ResponseWriter, r *http.Request, params GetArmoryParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get campaign state
// (GET /api/campaign-state)
func (_ Unimplemented) GetCampaignState(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Reset campaign
// (POST /api/campaign/reset)
func (_ Unimplemented) ResetCampaign(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get file content
// (GET /api/files)
func (_ Unimplemented) GetFileContent(w http.ResponseWriter, r *http.Request, params GetFileContentParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get attack flow
// (GET /api/flow)
func (_ Unimplemented) GetFlow(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Export attack flow
// (GET /api/flow/export)
func (_ Unimplemented) ExportAttackFlow(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Save attack flow
// (POST /api/flow/save)
func (_ Unimplemented) SaveFlow(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get attack graph
// (GET /api/graph)
func (_ Unimplemented) GetGraph(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get running pods
// (GET /api/pods/running)
func (_ Unimplemented) GetRunningPods(w http.ResponseWriter, r *http.Request, params GetRunningPodsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Stop watching pods
// (DELETE /api/pods/watch)
func (_ Unimplemented) StopPodWatch(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Start watching pods
// (POST /api/pods/watch)
func (_ Unimplemented) StartPodWatch(w http.ResponseWriter, r *http.Request, params StartPodWatchParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ExecuteAction operation middleware
func (siw *ServerInterfaceWrapper) ExecuteAction(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExecuteAction(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApplicableTTPs operation middleware
func (siw *ServerInterfaceWrapper) GetApplicableTTPs(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApplicableTTPsParams

	// ------------- Optional query parameter "targetId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "targetId", r.URL.Query(), &params.TargetId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "targetId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApplicableTTPs(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetArmory operation middleware
func (siw *ServerInterfaceWrapper) GetArmory(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetArmoryParams

	// ------------- Optional query parameter "tactic" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tactic", r.URL.Query(), &params.Tactic, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tactic", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetArmory(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCampaignState operation middleware
func (siw *ServerInterfaceWrapper) GetCampaignState(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCampaignState(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResetCampaign operation middleware
func (siw *ServerInterfaceWrapper) ResetCampaign(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResetCampaign(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetFileContent operation middleware
func (siw *ServerInterfaceWrapper) GetFileContent(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetFileContentParams

	// ------------- Required query parameter "path" -------------

	if paramValue := r.URL.Query().Get("path"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "path"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "path", r.URL.Query(), &params.Path, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFileContent(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetFlow operation middleware
func (siw *ServerInterfaceWrapper) GetFlow(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFlow(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ExportAttackFlow operation middleware
func (siw *ServerInterfaceWrapper) ExportAttackFlow(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExportAttackFlow(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SaveFlow operation middleware
func (siw *ServerInterfaceWrapper) SaveFlow(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SaveFlow(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGraph operation middleware
func (siw *ServerInterfaceWrapper) GetGraph(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGraph(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRunningPods operation middleware
func (siw *ServerInterfaceWrapper) GetRunningPods(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetRunningPodsParams

	// ------------- Optional query parameter "namespace" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "namespace", r.URL.Query(), &params.Namespace, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRunningPods(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StopPodWatch operation middleware
func (siw *ServerInterfaceWrapper) StopPodWatch(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StopPodWatch(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartPodWatch operation middleware
func (siw *ServerInterfaceWrapper) StartPodWatch(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params StartPodWatchParams

	// ------------- Optional query parameter "namespace" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "namespace", r.URL.Query(), &params.Namespace, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartPodWatch(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/action/execute", wrapper.ExecuteAction)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/applicable-ttps", wrapper.GetApplicableTTPs)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/armory", wrapper.GetArmory)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/campaign-state", wrapper.GetCampaignState)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/campaign/reset", wrapper.ResetCampaign)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/files", wrapper.GetFileContent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/flow", wrapper.GetFlow)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/flow/export", wrapper.ExportAttackFlow)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/flow/save", wrapper.SaveFlow)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/graph", wrapper.GetGraph)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/pods/running", wrapper.GetRunningPods)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/pods/watch", wrapper.StopPodWatch)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/pods/watch", wrapper.StartPodWatch)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RaW2/bOPb/KoT+f2A6gGJnO7OLbt7S9IKg3daIvZiHaR9o8UjihCJVknJqFPnuC150",
	"p2wrnaQzb05IHp7L71zFb1EiilJw4FpFF98ileRQYPvzUmuc3L5h4s78VUpRgtQU7BqQzP2gGgr74/8l",
	"pNFF9H/Llt7SE1u+JhlE93Gk9yVEFxGWEu/N31II/UEQuCaGgl9VWlKemWWloTz9EsfuWkM5vsrcBV8q",
	"KoFEF797wrGXosfH5+ao2P4BiTa0OpRHithsVscYM1vu4wjLzJ7AhFBNBcds1aM0En/ERyKKAvOwrsy9",
	"DDSQS23WUyELrKOLiGANZ5oWEMXjQwRS4ApOEOCV33kfR/AVkkoD+ciDjNAwf2KrQO7wlg1gMyV1g5FS",
	"igRIJadAIkFVTM8kqjSWM3WlNNaVwz6vCoOi//JbLu54FEdvMGVAojhaV0kCykDqI8+EOfk5QEpjmYEO",
	"yjMAKjVEcWLgcm1+NidbMMQWgn099YzkkRdHRjKlcVFGjTR9u7TK7Gqoj62Qf1zhosQ042uNNQRiBde0",
	"/n0E/C3N0T8kMGxO9i0dpqdlBfEkzXBMaLjsXhWS1gazkZATsOe4gAnYujtmC6FEJZMpZziArDi6A5rl",
	"fcSnTGDdop1XxRZkGIVWks71ncuCWpJSyLGaCGhMWdhJoT5y2CfctuCdDvSX1l+uCjK+vnGl0P3fH6CN",
	"1633SkMxccWxYHZ6ZAgFhZBO3kpc5o+Vv7kgM6iYDDu7ChiI7W48OXO/e6FuwEH2ZJe9pXymL5sFVeIk",
	"vFrm2KVYAiqRtHReH60EQXYJPbupOKc8i9EKOLE/bB4BAiRGLrfEyGebn0O5SQIm+/EVv+Wgc5AIM4YS",
	"wTWmHKRClCOdAyoFQVgCcocbqlshGGBepzy4AaxcmOoTv6oJnjHYAUN2syGmBEfPYJEt0JXEKn8vRPkS",
	"J7cf0zRG1wXOYFUx5v8TkOZA7LGWCZnZIivg7CYXvzfcTZZMUhRUQdfeHfltStjPjtDu2ISH/2mgK7EE",
	"rk8sIboK7DAY0uWqDlFjhR6qPyfkouq9SDC7Gp3sqFkLwU6Uo+YgxPjNy8urFciCKuXz6gAOJX0rRVVO",
	"8PmhdmLisJ7iiumBjTtMy05YCdWkdvHDdPZ3GzZ2IdT6JGJqxR68ESy8vAO5PSF71LrwBzryDLgf8Fpz",
	"1uNjoL6gcdzlRd1mzvNU+ErV3BJ/0qPkFictTk5PXwN8herJkdhrmhX4pmIBZyK+Vj61U+vE3m+hdQ3J",
	"g+rJCcdlImsBPoughBQk8ATm92S+wQqURdlMYprqoIMM/MBt8xd0he5qNHa2CsHad//DGvewrSBNIZkL",
	"Zzo/PeDidHBvNquVOXGwAz+dXJtEQvWeM8Bxh+vGjB5AjkiydhstcBJNk7CCIck5/VLNg+mB5No1e3Nz",
	"756O6D2tNtZqZJzA2qt2XjOA3C9mhUyEhsNwnIssZWLaMSu0ge8+jirJ5tQpE8I7fAa8zWfqB4h+oDuv",
	"GQsWLOGsPWxVcBvKOytDoNT8T0i9bkDfL7/d/5FIEUabzQqdoTtf7VONqELA8ZYBQUIiQpX9bSs/N7ry",
	"q+b6enE8qDICUZ6K8eU3QJAGXCBcaVHYOQbCnCBsB6Uo8fMgVGCOM+vA6HJ1HTVhObrB3P9nB9KVa9E/",
	"FueLczsqLIHjkkYX0S+L88Uv1j10bnWwxCVdutZ36UdcFhFC6TGXfhzgFeROIcMpch3zAm1yqP9/RxlD",
	"W0BfKqiAWGnqGRrCas+TXAouKsX27lhKOWZ+iznvHLcho4zMO4rRev16EVmZJK5nD/1BhQcHKP1SuC7O",
	"9Gq+tsdlyWhiTy7/8H2Y87GjPftwGHLfB6jJ3q4SLQVXzpeen5/Pur/viZMJfFwZ3Q+dM3J8tjpXbpKa",
	"VozZpPH8/PljsGYCtbqdmjycyrUHTSpki4gYla6b78EH2bCvFOVZF0cH0XMfR7/ONMxBYNj5WUCYa77D",
	"jBLk0eju/fXx7zVqUCUkNKXG2byfSu+l6A4rxIVGqag4cUz9+2mYqkMDVg0uY7StNErtTMbaW4minnpY",
	"yKiqKLDcd8OP83Kz6MKXY3bL4Exr930rAx0KsrqSXJngpZDOsUYJ5gYdloCJwMLOcVrV1WHtOkX1TNCk",
	"AlFQrV0qgKLU+xjJLmkjBWbMH1HjaPUW9GXDszlSFyygQaro4vch59evTF4yvHkTuoEDeiZK10XEtSiW",
	"nyEHP5uG0tD5UoHc11XBRffjR2vcodN+/s6Qdmq1HCgNRxhaNzEM1Tw9nVM5zXccpwfOt6BRC8QOELwR",
	"OnCVhZD7oyg19sM7TFlL79nG1sAqRpumBo5tZm3aA/XzAn30oGB7lFKmQaLtHrnyOYxFx9ARDNZUPSXj",
	"LC11O56M0Sfvo1TwT5H580oCMVjF7NJa7lM0jUVf3v+NkTgGhNNsY/q6jjtT9Ye9gxAwDp9UUprk1ZSA",
	"bix8R3WO6i9sFgLtN7aAifsfFL9Tj4fU17/owYrrSztW4FKCcpoLV6o3ZvmA/kY6sgdq5qO/ThVXs4Ss",
	"wKMi7p9PUcY4ZboUPbCVW6p129oppf5ZwnF8O9Zd31VK2FHbE9iPKCbAQAjObyiDKy/zkbDlSkIGyLQ8",
	"JmhJ0JLCrr05FXIiJpkj0bDEf8wINfw60BwLTKN0/kBIGeU1wtfaGPcHT5JUe7wcSq1pZ2MHZv4p1VGU",
	"+T7a7Heh0z5Yck2p//A5Bpkh/oihsvMa7OEJppWrr5UlfC2F1LOVQzn6z/Xm5jW63Gw+Vefnz/919Q4Z",
	"HpEfq487b3NPR5bv1NhR+E7UgE8SCZ2w4VDo16YtovDuwGxljXcwsoYWCIeDoNneqPths45+sKkDSsA/",
	"68ipahZTd/HhaZ0l+DkYjx51ZuIfjAXmjKcEx3UnClqByY+bFvTgZfERBFdWP0g5uZb0ZOxBFw7tK5DD",
	"4dC9e3nEeOgu+N5QmHkqXjmlIGop3XOQozpiVNlCxO9H5nD9uKMdCrSPUwJa8i9PVoIcberfVVuQHDSo",
	"lmS3o/dzbGWjAGPtpsl+vsvZD26juu+EHt7YP0lQd++BeqWhMXwAYl1cDCB2h3Xi4ycDDaHPC6Lse2Ep",
	"CLLHFuiDQIWQgH4ytM6SHPMMyE9ovX6NYGek6A0yx028Ib4S5DfLxF+nebH8IKVFWY4KzH5w06J0umjV",
	"G08lSo2lVgibDoHZz/vuJBLcnlyglSC+S3aabLVXVioHUg+CEVZDjTtthxSMpe5oeL5ja+HZ/Bt4+CNA",
	"wL59/jHta+vflg1nhhEAm5WOg5stIHdhK7+CHTBR2m9xblfkP8xGudblxXLJRIJZLpS+eHH+4jwyZrmD",
	"bS7ErXujY4dDZ0xg4r6LhvG+kTTLQAJBdzm4XOROIqp6CkWe0p9VEbav2098VHP/8GJvABqnJSQhARru",
	"TQOn6vrJ6xiVeG80MrC0G3Z6XdV7Daf3/wsAAP//pncnI7kzAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
