name: Release RanUI (deprecated)
on:
  workflow_dispatch: 
    inputs:
      app-name:
        description: "The name of the binary file"
        default: "RanUI"
        required: true
      # sign:
      #   description: "Sign the build"
      #   required: false
      #   default: "false"
      package:
        description: "Uploads workflow & uploads tag builds to a release"
        required: false
        default: "true"
      tag:
        description: "Existing release tag (e.g. v1.2.3)"
        required: true
        type: string
      build-platform:
        description: "Platform to build for"
        required: false
        default: "darwin/universal"
      # build-tags:
      #   description: "Build tags to pass to Go compiler. Must be quoted. Space or comma (but not both) separated"
      #   required: false
      #   default: "false"
      # build-obfuscate:
      #   description: "Obfuscate the build"
      #   required: false
      #   default: "false"
      wails-version:
        description: "Wails version to use"
        required: false
        default: "latest"
      wails-build-webview2:
        description: "Webview2 installer method [download,embed,browser,error]"
        required: false
        default: "download"
      app-working-directory:
        description: "This gets run into bash, use the full command"
        required: false
        default: "RanUI"

permissions:
  contents: write

jobs:
    build-wails:
      defaults:
          run: 
            working-directory: RanUI
      strategy:
      # Failure in one platform build won't impact the others
        fail-fast: false
        matrix:
          build: 
            - os: 'ubuntu-latest'
              platform:  'linux/amd64'
            - os: 'windows-latest'
              platform:  'windows/amd64'
            - os: 'macos-latest'
              platform:  'darwin/universal'
      runs-on: ${{ matrix.build.os }}
      steps:
        - name: Checkout
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
          with:
            submodules: recursive
        - name: Linux Discovery
          if: runner.os == 'Linux'
          id: linux_discovery
          run: |
            sudo apt-get -yq update
            DISTRO=$(lsb_release -rs) # Get the distribution version (e.g., "22.04", "24.04")
            if [[ "$DISTRO" == "20.04" ]]; then
              sudo apt-get -yq install libgtk-3-0 libwebkit2gtk-4.0-dev gcc-aarch64-linux-gnu
            elif [[ "$DISTRO" == "22.04" ]]; then
              sudo apt-get -yq install libgtk-3-0 libwebkit2gtk-4.0-dev gcc-aarch64-linux-gnu
            elif [[ "$DISTRO" == "24.04" ]]; then
              sudo apt-get -yq install libgtk-3-0 libwebkit2gtk-4.1-dev gcc-aarch64-linux-gnu
            else
              echo "Unsupported Linux distribution: $DISTRO"
              exit 1 # Fail the workflow if the distribution is not supported
            fi
            echo "DISTRO=$DISTRO" >> "$GITHUB_OUTPUT"
          shell: bash
        - name: Setup Build Options
          id: build_options
          shell: bash
          env:
            DISTRO: ${{ steps.linux_discovery.outputs.DISTRO }}
          run: |
            build_options=""
            if [[ "$DISTRO" == '24.04' ]]; then
              build_options+=" -tags webkit2_41"
            fi
            echo "BUILD_OPTIONS=$build_options" >> "$GITHUB_OUTPUT"
        # Setup and configure GoLang
        - name: Setup GoLang
          uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
          # if: inputs.wails-dev-build == 'false'
          with:
            check-latest: true
            cache: true
            cache-dependency-path: 'RanUI/go.sum'
            go-version-file: "RanUI/go.mod"
        # - name: Install Garble
        #   if: inputs.build-obfuscate == 'true'
        #   run: go install mvdan.cc/garble@latest
        #   shell: bash
        - run: go version
          shell: bash
        - name: Install pnpm
          uses: pnpm/action-setup@v4
          with:
            version: 10
        - name: Install Wails
          # if: inputs.build == 'true' && inputs.wails-dev-build == 'false'
          run: go install github.com/wailsapp/wails/v2/cmd/wails@${{inputs.wails-version}}
          shell: bash
        - name: Install macOS Wails deps
          if: runner.os == 'macOS'
          run: brew install mitchellh/gon/gon
          shell: bash
        # Building step
        - name: Build App
          env:
            BUILD_OPTIONS: ${{ steps.build_options.outputs.BUILD_OPTIONS }}
          working-directory: ${{ inputs.app-working-directory }}
          run: wails build --platform ${{ matrix.build.platform }} -webview2 ${{inputs.wails-build-webview2}} -o ${{inputs.app-name}} $BUILD_OPTIONS
          shell: bash
        - name: Add macOS perms
          if: runner.os == 'macOS'
          working-directory: ${{ inputs.app-working-directory }}
          run: chmod +x build/bin/*/Contents/MacOS/*
          shell: bash
        - name: Add Linux perms
          if: runner.os  == 'Linux'
          working-directory: ${{ inputs.app-working-directory }}
          run: chmod +x build/bin/*
          shell: bash
        # Package and Sign MacOS
        # - name: Import Code-Signing Certificates for macOS
        #   if: runner.os == 'macOS' && inputs.sign != 'false' && startsWith(github.ref, 'refs/tags/')
        #   uses: Apple-Actions/import-codesign-certs@v1
        #   with:
        #     keychain-password: ${{ inputs.sign-macos-apple-password }}
        #     p12-file-base64: ${{ inputs.sign-macos-app-cert }}
        #     p12-password: ${{ inputs.sign-macos-app-cert-password }}
        # - name: Import Code-Signing Certificates for macOS Installer
        #   if: runner.os == 'macOS' && inputs.sign != 'false' && startsWith(github.ref, 'refs/tags/')
        #   uses: Apple-Actions/import-codesign-certs@v1
        #   with:
        #     keychain-password: ${{ inputs.sign-macos-apple-password }}
        #     p12-file-base64: ${{ inputs.sign-macos-installer-cert }}
        #     p12-password: ${{ inputs.sign-macos-installer-cert-password }}
        #     create-keychain: false
        # - name: Sign our macOS binary
        #   if: runner.os == 'macOS' && inputs.sign != 'false' && startsWith(github.ref, 'refs/tags/')
        #   shell: bash
        #   working-directory: ${{ inputs.app-working-directory }}
        #   env:
        #     APPLE_PASSWORD: ${{ inputs.sign-macos-apple-password }}
        #   run: |
        #     echo "Signing Package"
        #     gon -log-level=info ./build/darwin/gon-sign.json
        - name: Build .tar.gz file
          if: runner.os == 'Linux'
          working-directory: ${{ inputs.app-working-directory }}
          shell: bash
          run: |
            tar -czvf dist/${{inputs.app-name}}_${{inputs.tag}}_linux_amd64.tar.gz -C build/bin/ ./${{inputs.app-name}}
        - name: Build .app zip file
          if: runner.os == 'macOS'
          working-directory: ${{ inputs.app-working-directory }}
          shell: bash
          run: |
            ditto -c -k -v --keepParent build/bin/${{inputs.app-name}}.app dist/${{inputs.app-name}}.app.zip
        # - name: Building Installer
        #   if: runner.os == 'macOS' && inputs.sign != 'false' && inputs.sign-macos-installer-id != '' && startsWith(github.ref, 'refs/tags/')
        #   shell: bash
        #   working-directory: ${{ inputs.app-working-directory }}
        #   run: |
        #     productbuild --sign '${{inputs.sign-macos-installer-id}}' --component ${{ inputs.app-working-directory }}/build/bin/${{inputs.app-name}}.app /Applications ${{ inputs.app-working-directory }}/build/bin/${{inputs.app-name}}.pkg
        - name: Building Installer
          if: runner.os == 'macOS' && startsWith(github.ref, 'refs/tags/')
          # if: runner.os == 'macOS' && inputs.sign-macos-installer-id == '' && startsWith(github.ref, 'refs/tags/')
          shell: bash
          working-directory: ${{ inputs.app-working-directory }}
          run: |
            productbuild --component build/bin/${{inputs.app-name}}.app /Applications dist/${{inputs.app-name}}.pkg
        # - name: Notarising Installer and zip
        #   if: runner.os == 'macOS' && inputs.sign != 'false' && startsWith(github.ref, 'refs/tags/')
        #   shell: bash
        #   working-directory: ${{ inputs.app-working-directory }}
        #   env:
        #     APPLE_PASSWORD: ${{ inputs.sign-macos-apple-password }}
        #   run: |
        #     gon -log-level=info ${{ inputs.app-working-directory }}/build/darwin/gon-notarize.json
        # # Windows signing
        # - name: Sign Windows binaries
        #   shell: powershell
        #   if: runner.os == 'Windows' && inputs.sign != 'false' && inputs.sign-windows-cert != ''
        #   working-directory: ${{ inputs.app-working-directory }}
        #   run: |
        #     echo "Creating certificate file"
        #     New-Item -ItemType directory -Path certificate
        #     Set-Content -Path certificate\certificate.txt -Value '${{ inputs.sign-windows-cert }}'
        #     certutil -decode certificate\certificate.txt certificate\certificate.pfx
        #     echo "Signing our binaries"
        #     & 'C:/Program Files (x86)/Windows Kits/10/bin/10.0.17763.0/x86/signtool.exe' sign /fd sha256 /tr http://ts.ssl.com /f certificate\certificate.pfx /p '${{ inputs.sign-windows-cert-password }}' .\build\bin\${{inputs.app-name}}.exe
        #     echo "Signing Installer" & 'C:/Program Files (x86)/Windows Kits/10/bin/10.0.17763.0/x86/signtool.exe' sign /fd sha256 /tr http://ts.ssl.com /f certificate\certificate.pfx /p '${{ inputs.sign-windows-cert-password }}' .\build\bin\${{inputs.app-name}}-amd64-installer.exe
        - name: List build content
          working-directory: ${{ inputs.app-working-directory }}
          run: find build | sed -e "s/[^-][^\/]*\//  |/g" -e "s/|\([^ ]\)/|-\1/"
        - name: List dist content
          working-directory: ${{ inputs.app-working-directory }}
          run: find dist | sed -e "s/[^-][^\/]*\//  |/g" -e "s/|\([^ ]\)/|-\1/"
          # Upload build assets
        - uses: actions/upload-artifact@v4
          if: inputs.package == 'true'
          with:
            name: ${{ inputs.app-name}}_${{inputs.tag}}_${{runner.os}}
            path: |
              ${{ inputs.app-working-directory }}/dist/*
              ${{ inputs.app-working-directory }}\dist\*

        - name: Upload to existing release
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # provided by Actions
          shell: bash
          working-directory: ${{ inputs.app-working-directory }}
          run: |
            TAG="${{ inputs.tag }}"
            gh release upload "$TAG" dist/* --clobber
