// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BroadcastMessage(arg1) {
  return window['go']['main']['App']['BroadcastMessage'](arg1);
}

export function ClientReady(arg1) {
  return window['go']['main']['App']['ClientReady'](arg1);
}

export function ExecuteAction(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExecuteAction'](arg1, arg2, arg3, arg4);
}

export function GetApplicableTTPs(arg1) {
  return window['go']['main']['App']['GetApplicableTTPs'](arg1);
}

export function GetArmory() {
  return window['go']['main']['App']['GetArmory']();
}

export function GetCampaignState() {
  return window['go']['main']['App']['GetCampaignState']();
}

export function GetFacts() {
  return window['go']['main']['App']['GetFacts']();
}

export function GetFlow() {
  return window['go']['main']['App']['GetFlow']();
}

export function GetGraph() {
  return window['go']['main']['App']['GetGraph']();
}

export function GetRunningPods(arg1) {
  return window['go']['main']['App']['GetRunningPods'](arg1);
}

export function ResetCampaign() {
  return window['go']['main']['App']['ResetCampaign']();
}

export function SaveFlow() {
  return window['go']['main']['App']['SaveFlow']();
}

export function SetContext(arg1) {
  return window['go']['main']['App']['SetContext'](arg1);
}

export function StartServer(arg1) {
  return window['go']['main']['App']['StartServer'](arg1);
}
