name: Use Kubeconfig 
description: Use an external kubeconfig file to access resources in the target cluster
tactic: InitialAccess
techniques:
  ["Valid Accounts: Cloud Accounts", T1078.004]
preconditions:
  kind: Cluster
parameters:
  Namespace: 
    type: Namespace
    description: The target namespace in which the target pod resides
  TargetName: 
    type: Pod
    description: The target pod to access using the external kubeconfig
procedures:
  - key: setTarget
    command: setTarget(${NAMESPACE}, ${TARGETNAME})
effects:
  - "Pod"
references:
  - "https://microsoft.github.io/Threat-Matrix-for-Kubernetes/techniques/Kubeconfig%20file/"
  - "https://kubenomicon.com/Initial_access/Kubeconfig_file.html"
